services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  backend:
    build: ./backend
    environment:
      SPRING_FRONTEND_URL: http://localhost
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/miobook
      SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: run/secrets/db_root_password
      # SPRING_JWT_SECRET: ${JWT_SECRET}
      # SPRING_OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
    secrets:
      - db_root_password
      - jwt_secret
      - oauth_google_client_secret
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: miobook
      MYSQL_ROOT_PASSWORD_FILE: run/secrets/db_root_password
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - db_root_password

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  oauth_google_client_secret:
    file: ./secrets/oauth_google_client_secret.txt

volumes:
  mysql_data: