services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: miobook
      MYSQL_ROOT_PASSWORD_FILE: run/secrets/db_root_password
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - db_root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$(cat /run/secrets/db_root_password)"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    image: mehdijmlkh/miobook-backend:latest
    build: ./backend
    environment:
      SPRING_FRONTEND_URL: http://localhost
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/miobook
      SPRING_DATASOURCE_USERNAME: root
    secrets:
      - db_root_password
      - jwt_secret
      - oauth_google_client_secret
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  frontend:
    image: mehdijmlkh/miobook-frontend:latest
    build: ./frontend
    ports:
      - "80:80"
    environment:
      BACKEND_DOMAIN: backend
    depends_on:
      backend:
        condition: service_healthy

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  oauth_google_client_secret:
    file: ./secrets/oauth_google_client_secret.txt

volumes:
  mysql_data: