apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_FRONTEND_URL: "http://localhost"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/miobook"
  SPRING_DATASOURCE_USERNAME: "root"