START TRANSACTION;

INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (1, 2, 'I expected more depth from the story.', CURRENT_DATE, 3, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (2, 5, 'The guide sections were clear and useful.', CURRENT_DATE, 3, 98);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (3, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 7, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (4, 5, 'Well written and easy to follow.', CURRENT_DATE, 10, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (5, 5, 'I expected more depth from the story.', CURRENT_DATE, 8, 92);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (6, 1, 'I learned a lot while reading this.', CURRENT_DATE, 9, 88);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (7, 3, 'A decent read for a quiet weekend.', CURRENT_DATE, 10, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (8, 5, 'I learned a lot while reading this.', CURRENT_DATE, 6, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (9, 1, 'Historical details were very immersive.', CURRENT_DATE, 7, 79);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (10, 5, 'I learned a lot while reading this.', CURRENT_DATE, 8, 74);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (11, 3, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 11, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (12, 5, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 7, 73);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (13, 2, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 6, 69);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (15, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 11, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (16, 4, 'Historical details were very immersive.', CURRENT_DATE, 10, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (17, 3, 'I learned a lot while reading this.', CURRENT_DATE, 9, 83);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (18, 5, 'The guide sections were clear and useful.', CURRENT_DATE, 7, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (19, 5, 'The adventure elements were exciting.', CURRENT_DATE, 3, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (20, 5, 'A decent read for a quiet weekend.', CURRENT_DATE, 5, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (21, 2, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 5, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (22, 3, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 6, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (23, 1, 'I expected more depth from the story.', CURRENT_DATE, 7, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (24, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 10, 68);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (25, 4, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 9, 91);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (26, 1, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 9, 64);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (27, 4, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 7, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (28, 5, 'I expected more depth from the story.', CURRENT_DATE, 8, 70);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (29, 1, 'The adventure elements were exciting.', CURRENT_DATE, 10, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (30, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 5, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (31, 2, 'The guide sections were clear and useful.', CURRENT_DATE, 7, 83);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (32, 1, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 11, 68);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (33, 2, 'A decent read for a quiet weekend.', CURRENT_DATE, 6, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (34, 5, 'I learned a lot while reading this.', CURRENT_DATE, 8, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (35, 3, 'Thrilling from beginning to end.', CURRENT_DATE, 4, 98);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (36, 1, 'A decent read for a quiet weekend.', CURRENT_DATE, 6, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (37, 2, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 8, 79);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (39, 4, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 6, 98);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (40, 5, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 7, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (41, 1, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 11, 69);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (42, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 5, 76);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (43, 1, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 10, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (44, 2, 'The guide sections were clear and useful.', CURRENT_DATE, 8, 73);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (45, 3, 'The guide sections were clear and useful.', CURRENT_DATE, 6, 80);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (46, 2, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 3, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (48, 3, 'Historical details were very immersive.', CURRENT_DATE, 6, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (49, 3, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 11, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (50, 2, 'Well written and easy to follow.', CURRENT_DATE, 3, 59);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (51, 2, 'Well written and easy to follow.', CURRENT_DATE, 6, 76);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (52, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 9, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (54, 5, 'I learned a lot while reading this.', CURRENT_DATE, 8, 80);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (55, 3, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 11, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (56, 1, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 10, 80);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (57, 3, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 4, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (58, 2, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 8, 69);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (59, 4, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 11, 86);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (62, 3, 'I expected more depth from the story.', CURRENT_DATE, 5, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (63, 3, 'I expected more depth from the story.', CURRENT_DATE, 11, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (64, 3, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 8, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (65, 5, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 3, 97);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (66, 4, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 6, 73);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (67, 4, 'The guide sections were clear and useful.', CURRENT_DATE, 2, 86);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (68, 2, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 11, 70);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (70, 1, 'The adventure elements were exciting.', CURRENT_DATE, 5, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (71, 1, 'Well written and easy to follow.', CURRENT_DATE, 5, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (72, 3, 'I expected more depth from the story.', CURRENT_DATE, 9, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (74, 1, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 3, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (75, 3, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 5, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (76, 3, 'I expected more depth from the story.', CURRENT_DATE, 11, 64);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (77, 4, 'Well written and easy to follow.', CURRENT_DATE, 8, 68);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (78, 3, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 5, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (79, 4, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 8, 86);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (80, 3, 'A decent read for a quiet weekend.', CURRENT_DATE, 10, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (81, 2, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 10, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (82, 1, 'Historical details were very immersive.', CURRENT_DATE, 11, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (83, 1, 'Historical details were very immersive.', CURRENT_DATE, 11, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (84, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 5, 88);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (85, 3, 'Thrilling from beginning to end.', CURRENT_DATE, 3, 88);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (86, 2, 'The adventure elements were exciting.', CURRENT_DATE, 6, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (87, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 2, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (88, 3, 'I learned a lot while reading this.', CURRENT_DATE, 3, 79);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (90, 5, 'The adventure elements were exciting.', CURRENT_DATE, 6, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (92, 1, 'The adventure elements were exciting.', CURRENT_DATE, 9, 73);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (93, 4, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 9, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (94, 4, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 5, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (95, 4, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 2, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (96, 5, 'The guide sections were clear and useful.', CURRENT_DATE, 6, 68);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (97, 2, 'Thrilling from beginning to end.', CURRENT_DATE, 5, 68);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (98, 1, 'The adventure elements were exciting.', CURRENT_DATE, 6, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (99, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 7, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (100, 4, 'The guide sections were clear and useful.', CURRENT_DATE, 4, 69);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (104, 1, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 4, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (105, 4, 'A decent read for a quiet weekend.', CURRENT_DATE, 7, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (106, 4, 'Well written and easy to follow.', CURRENT_DATE, 2, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (107, 2, 'Well written and easy to follow.', CURRENT_DATE, 10, 92);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (108, 3, 'The adventure elements were exciting.', CURRENT_DATE, 6, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (109, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 6, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (110, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 2, 70);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (113, 5, 'Thrilling from beginning to end.', CURRENT_DATE, 4, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (114, 3, 'The adventure elements were exciting.', CURRENT_DATE, 8, 59);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (115, 1, 'Well written and easy to follow.', CURRENT_DATE, 4, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (116, 3, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 11, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (117, 1, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 9, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (119, 5, 'I expected more depth from the story.', CURRENT_DATE, 9, 59);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (120, 5, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 5, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (121, 3, 'Well written and easy to follow.', CURRENT_DATE, 3, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (122, 5, 'Well written and easy to follow.', CURRENT_DATE, 7, 69);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (123, 5, 'I expected more depth from the story.', CURRENT_DATE, 5, 66);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (124, 2, 'I learned a lot while reading this.', CURRENT_DATE, 6, 92);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (125, 1, 'I learned a lot while reading this.', CURRENT_DATE, 2, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (126, 1, 'Well written and easy to follow.', CURRENT_DATE, 7, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (127, 3, 'I learned a lot while reading this.', CURRENT_DATE, 11, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (128, 3, 'I expected more depth from the story.', CURRENT_DATE, 7, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (129, 4, 'A decent read for a quiet weekend.', CURRENT_DATE, 10, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (130, 3, 'Well written and easy to follow.', CURRENT_DATE, 9, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (131, 5, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 11, 95);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (133, 2, 'Thrilling from beginning to end.', CURRENT_DATE, 3, 74);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (134, 5, 'Historical details were very immersive.', CURRENT_DATE, 8, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (137, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 8, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (138, 3, 'A decent read for a quiet weekend.', CURRENT_DATE, 8, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (140, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 10, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (143, 3, 'Well written and easy to follow.', CURRENT_DATE, 5, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (144, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 9, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (148, 3, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 2, 66);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (150, 2, 'I expected more depth from the story.', CURRENT_DATE, 11, 80);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (151, 5, 'I expected more depth from the story.', CURRENT_DATE, 2, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (153, 4, 'I expected more depth from the story.', CURRENT_DATE, 6, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (154, 3, 'Thrilling from beginning to end.', CURRENT_DATE, 2, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (155, 1, 'The guide sections were clear and useful.', CURRENT_DATE, 10, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (157, 1, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 10, 59);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (158, 1, 'Thrilling from beginning to end.', CURRENT_DATE, 4, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (159, 1, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 8, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (160, 5, 'I expected more depth from the story.', CURRENT_DATE, 6, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (161, 4, 'A decent read for a quiet weekend.', CURRENT_DATE, 6, 97);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (162, 3, 'The guide sections were clear and useful.', CURRENT_DATE, 10, 64);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (163, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 8, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (164, 1, 'Historical details were very immersive.', CURRENT_DATE, 11, 88);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (165, 3, 'The guide sections were clear and useful.', CURRENT_DATE, 10, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (168, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 2, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (171, 4, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 10, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (173, 4, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 3, 66);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (174, 2, 'I expected more depth from the story.', CURRENT_DATE, 8, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (175, 4, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 9, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (176, 5, 'I learned a lot while reading this.', CURRENT_DATE, 9, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (177, 1, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 4, 74);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (178, 4, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 5, 73);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (180, 3, 'The adventure elements were exciting.', CURRENT_DATE, 2, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (181, 2, 'The adventure elements were exciting.', CURRENT_DATE, 7, 70);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (184, 1, 'Thrilling from beginning to end.', CURRENT_DATE, 11, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (185, 4, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 7, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (187, 2, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 9, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (188, 3, 'Historical details were very immersive.', CURRENT_DATE, 4, 95);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (189, 3, 'I expected more depth from the story.', CURRENT_DATE, 11, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (190, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 8, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (193, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 8, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (194, 2, 'The guide sections were clear and useful.', CURRENT_DATE, 4, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (195, 1, 'Thrilling from beginning to end.', CURRENT_DATE, 10, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (197, 3, 'A decent read for a quiet weekend.', CURRENT_DATE, 2, 92);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (198, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 2, 74);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (201, 3, 'I expected more depth from the story.', CURRENT_DATE, 11, 79);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (203, 5, 'I expected more depth from the story.', CURRENT_DATE, 7, 68);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (205, 5, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 5, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (207, 2, 'I expected more depth from the story.', CURRENT_DATE, 10, 66);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (210, 4, 'A decent read for a quiet weekend.', CURRENT_DATE, 8, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (211, 2, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 6, 83);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (212, 1, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 3, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (213, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 5, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (215, 1, 'Historical details were very immersive.', CURRENT_DATE, 4, 66);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (217, 4, 'Thrilling from beginning to end.', CURRENT_DATE, 7, 66);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (221, 3, 'Well written and easy to follow.', CURRENT_DATE, 2, 95);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (222, 4, 'Thrilling from beginning to end.', CURRENT_DATE, 6, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (223, 5, 'The guide sections were clear and useful.', CURRENT_DATE, 7, 97);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (224, 5, 'The adventure elements were exciting.', CURRENT_DATE, 6, 59);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (226, 1, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 4, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (228, 5, 'A decent read for a quiet weekend.', CURRENT_DATE, 4, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (229, 1, 'A decent read for a quiet weekend.', CURRENT_DATE, 4, 91);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (230, 5, 'A decent read for a quiet weekend.', CURRENT_DATE, 10, 91);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (231, 2, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 8, 98);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (233, 4, 'I expected more depth from the story.', CURRENT_DATE, 7, 98);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (234, 2, 'The adventure elements were exciting.', CURRENT_DATE, 2, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (236, 2, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 3, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (237, 5, 'Thrilling from beginning to end.', CURRENT_DATE, 5, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (238, 4, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 3, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (241, 5, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 8, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (242, 5, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 6, 74);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (243, 5, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 6, 66);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (244, 2, 'The guide sections were clear and useful.', CURRENT_DATE, 7, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (247, 1, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 9, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (249, 4, 'I expected more depth from the story.', CURRENT_DATE, 3, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (250, 4, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 10, 86);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (251, 1, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 11, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (252, 1, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 11, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (254, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 10, 83);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (255, 2, 'A decent read for a quiet weekend.', CURRENT_DATE, 8, 97);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (260, 5, 'I learned a lot while reading this.', CURRENT_DATE, 11, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (263, 5, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 5, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (264, 3, 'Well written and easy to follow.', CURRENT_DATE, 10, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (267, 5, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 4, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (268, 3, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 5, 80);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (269, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 4, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (271, 4, 'The guide sections were clear and useful.', CURRENT_DATE, 5, 59);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (272, 1, 'Well written and easy to follow.', CURRENT_DATE, 8, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (273, 1, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 9, 80);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (274, 3, 'The adventure elements were exciting.', CURRENT_DATE, 6, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (275, 5, 'Historical details were very immersive.', CURRENT_DATE, 5, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (277, 1, 'Thrilling from beginning to end.', CURRENT_DATE, 3, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (282, 1, 'The adventure elements were exciting.', CURRENT_DATE, 6, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (283, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 3, 86);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (286, 4, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 4, 86);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (289, 5, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 10, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (290, 5, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 5, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (292, 2, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 7, 59);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (294, 1, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 4, 92);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (304, 4, 'Well written and easy to follow.', CURRENT_DATE, 4, 76);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (306, 3, 'Thrilling from beginning to end.', CURRENT_DATE, 4, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (310, 2, 'I expected more depth from the story.', CURRENT_DATE, 10, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (315, 4, 'The guide sections were clear and useful.', CURRENT_DATE, 5, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (318, 4, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 4, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (319, 1, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 10, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (321, 4, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 5, 69);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (323, 3, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 5, 70);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (324, 1, 'A decent read for a quiet weekend.', CURRENT_DATE, 10, 76);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (326, 3, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 3, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (328, 3, 'A decent read for a quiet weekend.', CURRENT_DATE, 4, 70);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (329, 1, 'Thrilling from beginning to end.', CURRENT_DATE, 7, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (332, 4, 'Historical details were very immersive.', CURRENT_DATE, 2, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (334, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 6, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (335, 4, 'The adventure elements were exciting.', CURRENT_DATE, 10, 79);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (337, 4, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 6, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (340, 5, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 10, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (344, 1, 'Well written and easy to follow.', CURRENT_DATE, 7, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (346, 4, 'The guide sections were clear and useful.', CURRENT_DATE, 9, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (347, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 4, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (350, 2, 'Well written and easy to follow.', CURRENT_DATE, 4, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (354, 3, 'A decent read for a quiet weekend.', CURRENT_DATE, 4, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (357, 4, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 11, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (360, 2, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 8, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (363, 4, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 9, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (364, 4, 'The guide sections were clear and useful.', CURRENT_DATE, 2, 80);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (365, 3, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 10, 98);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (366, 3, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 9, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (367, 3, 'The guide sections were clear and useful.', CURRENT_DATE, 6, 91);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (369, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 2, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (373, 2, 'I expected more depth from the story.', CURRENT_DATE, 4, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (374, 5, 'I learned a lot while reading this.', CURRENT_DATE, 3, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (375, 3, 'I learned a lot while reading this.', CURRENT_DATE, 9, 97);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (376, 1, 'Historical details were very immersive.', CURRENT_DATE, 6, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (377, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 3, 80);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (378, 5, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 7, 91);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (380, 3, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 10, 73);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (385, 3, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 5, 91);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (389, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 9, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (391, 4, 'Historical details were very immersive.', CURRENT_DATE, 4, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (392, 2, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 9, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (395, 3, 'Thrilling from beginning to end.', CURRENT_DATE, 9, 68);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (396, 4, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 7, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (399, 5, 'I expected more depth from the story.', CURRENT_DATE, 8, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (401, 5, 'Thrilling from beginning to end.', CURRENT_DATE, 5, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (402, 2, 'I learned a lot while reading this.', CURRENT_DATE, 4, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (404, 4, 'The adventure elements were exciting.', CURRENT_DATE, 8, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (408, 2, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 8, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (409, 4, 'Well written and easy to follow.', CURRENT_DATE, 11, 91);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (415, 1, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 3, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (419, 3, 'I expected more depth from the story.', CURRENT_DATE, 3, 83);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (421, 5, 'Thrilling from beginning to end.', CURRENT_DATE, 7, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (427, 5, 'The guide sections were clear and useful.', CURRENT_DATE, 8, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (429, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 4, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (431, 3, 'Historical details were very immersive.', CURRENT_DATE, 2, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (433, 1, 'I expected more depth from the story.', CURRENT_DATE, 6, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (435, 3, 'Well written and easy to follow.', CURRENT_DATE, 3, 68);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (438, 5, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 7, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (439, 1, 'Thrilling from beginning to end.', CURRENT_DATE, 9, 66);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (445, 2, 'Well written and easy to follow.', CURRENT_DATE, 11, 74);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (449, 4, 'Historical details were very immersive.', CURRENT_DATE, 9, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (452, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 8, 100);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (456, 3, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 7, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (457, 2, 'A decent read for a quiet weekend.', CURRENT_DATE, 10, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (461, 5, 'Well written and easy to follow.', CURRENT_DATE, 11, 59);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (462, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 5, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (464, 3, 'The adventure elements were exciting.', CURRENT_DATE, 9, 76);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (465, 5, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 8, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (466, 4, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 4, 97);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (469, 1, 'Historical details were very immersive.', CURRENT_DATE, 10, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (471, 1, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 9, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (472, 3, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 11, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (473, 4, 'Well written and easy to follow.', CURRENT_DATE, 9, 95);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (475, 5, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 4, 83);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (478, 2, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 9, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (479, 3, 'The guide sections were clear and useful.', CURRENT_DATE, 6, 64);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (484, 5, 'I learned a lot while reading this.', CURRENT_DATE, 5, 64);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (486, 4, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 11, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (489, 2, 'I expected more depth from the story.', CURRENT_DATE, 10, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (492, 1, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 3, 64);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (494, 2, 'Well written and easy to follow.', CURRENT_DATE, 10, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (495, 3, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 9, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (502, 5, 'I learned a lot while reading this.', CURRENT_DATE, 10, 88);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (503, 5, 'Well written and easy to follow.', CURRENT_DATE, 5, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (504, 2, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 2, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (507, 1, 'I expected more depth from the story.', CURRENT_DATE, 2, 79);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (511, 5, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 11, 98);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (512, 1, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 4, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (513, 2, 'Thrilling from beginning to end.', CURRENT_DATE, 3, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (514, 4, 'I expected more depth from the story.', CURRENT_DATE, 6, 89);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (517, 1, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 4, 88);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (524, 5, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 2, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (527, 3, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 5, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (528, 3, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 7, 86);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (536, 5, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 6, 79);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (541, 4, 'The guide sections were clear and useful.', CURRENT_DATE, 6, 94);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (543, 5, 'The guide sections were clear and useful.', CURRENT_DATE, 5, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (548, 2, 'Well written and easy to follow.', CURRENT_DATE, 7, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (549, 3, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 8, 83);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (552, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 3, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (560, 3, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 9, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (562, 1, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 11, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (563, 3, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 8, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (570, 1, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 8, 96);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (578, 5, 'Historical details were very immersive.', CURRENT_DATE, 11, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (585, 3, 'The guide sections were clear and useful.', CURRENT_DATE, 3, 69);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (592, 1, 'Historical details were very immersive.', CURRENT_DATE, 7, 95);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (598, 2, 'The guide sections were clear and useful.', CURRENT_DATE, 11, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (599, 4, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 6, 95);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (601, 3, 'Thrilling from beginning to end.', CURRENT_DATE, 11, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (608, 1, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 2, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (609, 3, 'Well written and easy to follow.', CURRENT_DATE, 5, 92);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (613, 3, 'Well written and easy to follow.', CURRENT_DATE, 8, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (615, 2, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 8, 88);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (622, 5, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 3, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (623, 2, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 4, 77);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (627, 5, 'A decent read for a quiet weekend.', CURRENT_DATE, 9, 74);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (636, 5, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 7, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (638, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 7, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (643, 2, 'I really enjoyed this book and found the story engaging.', CURRENT_DATE, 3, 76);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (644, 2, 'Well written and easy to follow.', CURRENT_DATE, 11, 92);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (645, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 3, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (647, 5, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 5, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (654, 2, 'I expected more depth from the story.', CURRENT_DATE, 4, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (657, 4, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 5, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (662, 1, 'Thrilling from beginning to end.', CURRENT_DATE, 6, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (670, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 5, 79);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (671, 5, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 9, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (683, 2, 'Historical details were very immersive.', CURRENT_DATE, 7, 57);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (686, 1, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 2, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (706, 1, 'The adventure elements were exciting.', CURRENT_DATE, 3, 87);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (707, 2, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 10, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (710, 2, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 11, 93);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (724, 1, 'I learned a lot while reading this.', CURRENT_DATE, 2, 67);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (731, 3, 'The guide sections were clear and useful.', CURRENT_DATE, 6, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (736, 1, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 5, 95);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (751, 5, 'I learned a lot while reading this.', CURRENT_DATE, 9, 65);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (754, 5, 'A decent read for a quiet weekend.', CURRENT_DATE, 2, 78);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (760, 3, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 9, 86);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (762, 2, 'I expected more depth from the story.', CURRENT_DATE, 7, 84);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (763, 4, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 7, 85);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (766, 2, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 10, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (768, 5, 'The guide sections were clear and useful.', CURRENT_DATE, 11, 73);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (775, 4, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 5, 97);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (779, 2, 'Well written and easy to follow.', CURRENT_DATE, 11, 58);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (786, 4, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 3, 91);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (789, 4, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 2, 88);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (807, 2, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 7, 76);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (809, 1, 'I learned a lot while reading this.', CURRENT_DATE, 7, 64);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (813, 1, 'Plot twists made this a very entertaining experience.', CURRENT_DATE, 3, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (830, 4, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 11, 97);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (833, 2, 'I expected more depth from the story.', CURRENT_DATE, 6, 75);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (842, 5, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 7, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (843, 2, 'I learned a lot while reading this.', CURRENT_DATE, 2, 64);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (846, 3, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 9, 92);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (849, 5, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 8, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (851, 1, 'Historical details were very immersive.', CURRENT_DATE, 4, 82);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (864, 2, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 3, 99);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (867, 1, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 10, 71);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (869, 5, 'The pacing was a little slow but overall it was a good read.', CURRENT_DATE, 2, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (872, 3, 'A fantastic book that kept me turning pages.', CURRENT_DATE, 3, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (877, 3, 'The adventure elements were exciting.', CURRENT_DATE, 11, 61);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (887, 4, 'A decent read for a quiet weekend.', CURRENT_DATE, 10, 70);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (900, 3, 'Well written and easy to follow.', CURRENT_DATE, 5, 83);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (913, 2, 'Not my favorite but it still had some memorable moments.', CURRENT_DATE, 9, 72);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (917, 3, 'A decent read for a quiet weekend.', CURRENT_DATE, 9, 60);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (918, 5, 'I learned a lot while reading this.', CURRENT_DATE, 7, 74);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (924, 2, 'Characters were interesting and the setting felt vivid.', CURRENT_DATE, 9, 81);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (928, 2, 'Some parts dragged but the ending was satisfying.', CURRENT_DATE, 3, 62);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (947, 3, 'The guide sections were clear and useful.', CURRENT_DATE, 4, 73);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (967, 4, 'I expected more depth from the story.', CURRENT_DATE, 3, 95);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (968, 5, 'Well written and easy to follow.', CURRENT_DATE, 3, 63);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (969, 3, 'The adventure elements were exciting.', CURRENT_DATE, 9, 98);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (984, 2, 'The adventure elements were exciting.', CURRENT_DATE, 11, 90);
INSERT INTO reviews (id, rate, comment, date, customer_id, book_id) VALUES (991, 4, 'Historical details were very immersive.', CURRENT_DATE, 8, 76);

COMMIT;