START TRANSACTION;

INSERT INTO genres (id, name) VALUES (1, 'Adventure');
INSERT INTO genres (id, name) VALUES (2, 'Guide');
INSERT INTO genres (id, name) VALUES (3, 'Historic');
INSERT INTO genres (id, name) VALUES (4, 'Historical');
INSERT INTO genres (id, name) VALUES (5, 'Thriller');

INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (1, 'Shadows of the North', 'Maple Leaf Press', 2015, 1499, 'A detective uncovers secrets in a frozen town.', 'A fast-paced thriller set in northern Canada.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (2, 'Empire of Ash', 'Roma Books', 2018, 1950, 'A fallen empire fights for survival.', 'An epic journey through war and betrayal.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (3, 'Silent Tides', 'Sora Publishing', 2021, 1675, 'A sailor confronts a hidden conspiracy.', 'Mystery unfolds across the Pacific Ocean.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (4, 'Celtic Whispers', 'Emerald House', 1978, 1200, 'Legends come alive in rural Ireland.', 'A historical tale of myth and rebellion.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (5, 'London Veil', 'Sterling Press', 1992, 1345, 'A journalist uncovers a political scandal.', 'A suspenseful thriller in modern London.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (6, 'Arctic Fire', 'Maple Leaf Press', 2017, 1520, 'Explorers search for a lost expedition.', 'Adventure across icy wilderness.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (7, 'Samurai Code', 'Sora Publishing', 2019, 1800, 'A modern man discovers ancient honor.', 'Historical intrigue meets present danger.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (8, 'Roman Shadows', 'Roma Books', 2020, 1780, 'Secrets beneath the Colosseum.', 'An archaeological adventure.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (9, 'Emerald Storm', 'Emerald House', 1985, 1160, 'A family torn by rebellion.', 'Drama set during Irish uprising.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (10, 'Midnight Protocol', 'Sterling Press', 2001, 1420, 'Espionage in the digital age.', 'A spy races against time.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (11, 'Frozen Echoes', 'Maple Leaf Press', 2014, 1390, 'Voices from an abandoned town.', 'Mystery buried under snow.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (12, 'Gladiator''s Oath', 'Roma Books', 2016, 1840, 'A slave fights for freedom.', 'Historical drama in ancient Rome.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (13, 'Pacific Run', 'Sora Publishing', 2022, 1910, 'A chase across island nations.', 'High-speed maritime thriller.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (14, 'Highland Guide', 'Emerald House', 1990, 1050, 'A traveler''s handbook to Irish highlands.', 'Cultural and historical insights.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (15, 'Cipher of Kings', 'Sterling Press', 2005, 1500, 'A code hidden in royal archives.', 'Thriller blending history and espionage.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (16, 'Crimson Harbor', 'Maple Leaf Press', 2020, 1650, 'A murder investigation in a foggy port.', 'A detective faces old enemies as new threats emerge.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (17, 'Vestal''s Secret', 'Roma Books', 2022, 2000, 'A forbidden love in ancient Rome.', 'History and romance collide in perilous times.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (18, 'Wind Chaser', 'Sora Publishing', 2017, 1700, 'A pilot races a deadly storm.', 'Adventure above the Pacific Rim.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (19, 'Emerald Pathways', 'Emerald House', 1995, 1230, 'A walking guide to Ireland''s hidden wilds.', 'Stories and secrets in each step.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (20, 'Parliament Plots', 'Sterling Press', 1997, 1380, 'Deadly games in the halls of power.', 'A political thriller with global stakes.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (21, 'Mistwood Incident', 'Maple Leaf Press', 2013, 1190, 'When strange events haunt a small town.', 'Superstition clashes with science.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (22, 'Augustus'' Heir', 'Roma Books', 2018, 1820, 'A conspiracy threatening the Roman throne.', 'Loyalty and betrayal in imperial Rome.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (23, 'Midnight Sakura', 'Sora Publishing', 2024, 2000, 'A secret exchange beneath cherry blossoms.', 'International agents and ancient legends cross paths.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (24, 'Lakeside Legends', 'Emerald House', 1988, 1100, 'True tales from Irish lakes.', 'History, myth, and folklore blend along the shore.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (25, 'Silent Decree', 'Sterling Press', 2010, 1650, 'An order that cannot be spoken aloud.', 'An agent races the clock to prevent disaster.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (26, 'North Shore Guide', 'Maple Leaf Press', 2022, 1370, 'Practical travel tips for Canada''s northern coast.', 'Destinations, culture, and what to pack.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (27, 'Trial of Spears', 'Roma Books', 2019, 1790, 'A warrior faces a deadly rite of passage.', 'Adventure deep in tribal Gaul.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (28, 'Samurai''s Map', 'Sora Publishing', 2021, 1660, 'Cryptic clues lead to a centuries-old secret.', 'Guided by honor to hidden treasures.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (29, 'County Passage', 'Emerald House', 1981, 1070, 'A guide through rural Ireland''s heart.', 'Maps and folklore for travelers.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (30, 'Veil of Shadows', 'Sterling Press', 1990, 1350, 'A master thief in Victorian London.', 'Lamp-lit adventure and dangerous intrigue.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (31, 'Aurora Peril', 'Maple Leaf Press', 2016, 1550, 'A guide lost under mysterious northern lights.', 'Isolation breeds suspense and discovery.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (32, 'Sabine''s War', 'Roma Books', 2023, 2150, 'A woman’s journey in a Roman civil war.', 'Courage and loss in a turbulent era.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (33, 'Tokyo Routes', 'Sora Publishing', 2020, 1450, 'A travel guide for hidden Tokyo.', 'Cultural tips and off-path sites.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (34, 'Ireland Unveiled', 'Emerald House', 1975, 1220, 'The history of Ireland''s lesser-known clans.', 'A centuries-spanning journey of discovery.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (35, 'Royal Code', 'Sterling Press', 2007, 1480, 'A cipher connecting royal assassinations.', 'Secret societies and ancient intrigues.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (36, 'Glacier’s Eye', 'Maple Leaf Press', 2019, 1570, 'Scientists uncover a deadly threat frozen for centuries.', 'Race for survival against nature and man.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (37, 'Frontier Flames', 'Roma Books', 2014, 1960, 'Rome’s frontiers erupt in rebellion.', 'Adventure at the far edge of empire.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (38, 'Kanto Data', 'Sora Publishing', 2023, 1890, 'A guide through Japan''s digital underworld.', 'Tech, travel, and tales from Tokyo.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (39, 'Ring Fort Adventure', 'Emerald House', 1986, 1290, 'A treasure hunt beneath an ancient ring fort.', 'Legends lead to real-life adventure.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (40, 'Siege of Truth', 'Sterling Press', 2000, 1560, 'A journalist trapped by faith and lies.', 'A dark thriller plays out in hiding.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (41, 'Polar Guide', 'Maple Leaf Press', 2017, 1360, 'Survival guide for extreme environments.', 'From navigation to wildlife tips.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (42, 'Falcon Standard', 'Roma Books', 2016, 2110, 'A lost legionnaire must reclaim Rome’s honor.', 'A journey through unfamiliar lands.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (43, 'Silent Pavilion', 'Sora Publishing', 2022, 1720, 'A cult hides a secret in a Kyoto temple.', 'Ancient rites, present danger.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (44, 'Famine to Feast', 'Emerald House', 1983, 1270, 'Stories from the Irish famine.', 'An emotional journey through hardship.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (45, 'Harbor Lights', 'Sterling Press', 2012, 1620, 'A series of coded messages threaten the city.', 'A race against time by sea and land.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (46, 'Cedar Trails', 'Maple Leaf Press', 2023, 1490, 'Nature guide to Canada’s hidden forests.', 'Maps, tips, and personal stories.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (47, 'Chariots of Dawn', 'Roma Books', 2021, 2180, 'Epic chariot races challenge the powerful.', 'High stakes and high drama under Roman law.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (48, 'Dragon Roads', 'Sora Publishing', 2020, 1630, 'Adventurers seek truth through old legends.', 'A magical journey across Japan.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (49, 'Moss & Stone', 'Emerald House', 1989, 1030, 'Guide to Ireland''s unique stone architecture.', 'History preserved in mossy ruins.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (50, 'Legacy Watch', 'Sterling Press', 2011, 1360, 'A hidden inheritance leads to peril.', 'Uncovering secrets before time runs out.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (51, 'Crossing the Divide', 'Maple Leaf Press', 2021, 1530, 'Two explorers braved icy wilderness for science.', 'Narrative of survival and discovery.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (52, 'Brutus'' Paradox', 'Roma Books', 2015, 1860, 'The story behind Julius Caesar''s betrayer.', 'A man torn between duty and friendship.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (53, 'Tidal Secrets', 'Sora Publishing', 2019, 1750, 'Divers discover a deadly message.', 'A thrilling race against ocean tides.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (54, 'Gaelic Vistas', 'Emerald House', 1982, 1160, 'A tour of Ireland’s natural wonders.', 'Scenic routes and ancient stories.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (55, 'Protocol Omega', 'Sterling Press', 2003, 1410, 'Global catastrophe, only one key.', 'Teams race to stop a cyber attack.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (56, 'Red Forest', 'Maple Leaf Press', 2018, 1610, 'Strange events haunt researchers.', 'Old legends awaken in the woods.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (57, 'Harbor of Glass', 'Sterling Press', 2006, 1490, 'A smuggling ring hides secrets in plain sight.', 'A relentless investigation unfolds along the Thames.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (58, 'Northern Compass', 'Maple Leaf Press', 2024, 1740, 'A practical handbook for remote expeditions.', 'Field-tested advice for navigating the far north.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (59, 'Legion of Sand', 'Roma Books', 2017, 2040, 'Roman soldiers battle across desert frontiers.', 'An epic campaign where loyalty is tested.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (60, 'Hidden Shogunate', 'Sora Publishing', 2021, 1830, 'A historian uncovers a suppressed chapter of Japan.', 'Ancient secrets clash with modern politics.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (61, 'Riverstone Legends', 'Emerald House', 1979, 1140, 'Folklore passed down along quiet Irish rivers.', 'Stories blending myth, memory, and local history.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (62, 'Icebreaker Run', 'Maple Leaf Press', 2018, 1580, 'A convoy trapped in Arctic waters.', 'Survival and sabotage collide in frozen seas.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (63, 'Senator''s Game', 'Roma Books', 2020, 1990, 'A senator manipulates power in ancient Rome.', 'Political intrigue threatens the empire.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (64, 'Kyoto Lantern Guide', 'Sora Publishing', 2016, 1320, 'A cultural guide to Kyoto’s lantern festivals.', 'Travel tips, traditions, and hidden alleys.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (65, 'Stone Circle Quest', 'Emerald House', 1987, 1260, 'Explorers search for meaning behind ancient circles.', 'Adventure mixed with Celtic history.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (66, 'Terminal Cipher', 'Sterling Press', 2014, 1570, 'A hacker reveals a plot threatening global finance.', 'A high-tech chase across continents.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (67, 'Whispering Pines', 'Maple Leaf Press', 2012, 1280, 'Campers hear voices deep in the forest.', 'A mystery unfolds under towering pines.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (68, 'Standard of the Eagle', 'Roma Books', 2013, 1870, 'A Roman legion’s honor hangs by a thread.', 'Soldiers trek across hostile lands to reclaim glory.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (69, 'Shinobi Passage', 'Sora Publishing', 2024, 1910, 'A secret ninja route rediscovered.', 'An academic becomes entangled in espionage.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (70, 'Old Abbey Trails', 'Emerald House', 1992, 1090, 'Guide to Ireland’s medieval abbeys.', 'Architecture, legends, and traveler notes.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (71, 'Dark Ledger', 'Sterling Press', 2008, 1430, 'An accountant uncovers a criminal empire.', 'Financial secrets spiral into danger.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (72, 'Aurora Trails Guide', 'Maple Leaf Press', 2020, 1390, 'Best routes to witness the northern lights.', 'Travel planning with science insights.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (73, 'Centurion’s Path', 'Roma Books', 2011, 1760, 'A veteran soldier seeks redemption.', 'Battlefields and loyalty shape destiny.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (74, 'Harbor of Kites', 'Sora Publishing', 2015, 1620, 'A seaside town hides an ancient message.', 'Children’s kites reveal a coded map.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (75, 'Island Wayfinder', 'Emerald House', 1984, 1110, 'A traveler’s guide to Ireland’s western islands.', 'Routes, history, and cultural highlights.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (76, 'Shadow Cabinet', 'Sterling Press', 2016, 1640, 'A secret council manipulates world events.', 'A reporter risks everything to expose truth.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (77, 'Boreal Crossing', 'Maple Leaf Press', 2025, 1860, 'Explorers traverse Canada’s deepest wilderness.', 'Nature challenges every step forward.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (78, 'Forum Conspiracy', 'Roma Books', 2012, 1810, 'Plots form beneath the Roman Forum.', 'Power struggles erupt in marble halls.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (79, 'Temple Cipher', 'Sora Publishing', 2023, 1880, 'Symbols carved in temples reveal a map.', 'A scholar races thieves to the truth.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (80, 'Fields of Tara', 'Emerald House', 1991, 1200, 'A narrative history of Ireland’s sacred hill.', 'Kings, myths, and archaeology intertwine.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (81, 'Signal at Dawn', 'Sterling Press', 2009, 1470, 'A mysterious radio broadcast sparks panic.', 'Agents race to track its origin.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (82, 'Timberline Manual', 'Maple Leaf Press', 2021, 1340, 'Outdoor survival tips for mountain forests.', 'Tools, trails, and techniques.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (83, 'Empire’s Last Road', 'Roma Books', 2024, 2200, 'A final mission along Rome’s fading borders.', 'A soldier witnesses the empire’s twilight.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (84, 'Neon Harbor', 'Sora Publishing', 2018, 1730, 'A futuristic port hides a dangerous smuggling ring.', 'Detectives follow neon-lit clues.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (85, 'Cliffs of Clare Guide', 'Emerald House', 1980, 1080, 'Visitor guide to Ireland’s famous cliffs.', 'Geology, folklore, and travel advice.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (86, 'Operation Nightfall', 'Sterling Press', 2018, 1690, 'A covert mission spirals into chaos.', 'An agent uncovers betrayal within his ranks.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (87, 'Snowline Echo', 'Maple Leaf Press', 2015, 1480, 'Climbers hear signals from a lost expedition.', 'An icy trail leads to long-buried truth.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (88, 'Praetorian Vow', 'Roma Books', 2010, 1700, 'An elite guard questions loyalty to the emperor.', 'Duty and morality collide in Rome.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (89, 'Shoreline Atlas', 'Sora Publishing', 2017, 1410, 'A traveler’s atlas of Japan’s coastal towns.', 'Local foods, festivals, and maps.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (90, 'Ballad of the Green Road', 'Emerald House', 1993, 1190, 'Travel stories along Ireland’s longest road.', 'History and humor from roadside villages.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (91, 'Iron Gate Affair', 'Sterling Press', 2004, 1400, 'A diplomat vanishes during tense negotiations.', 'A global search reveals hidden alliances.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (92, 'Crimson Wake', 'Sterling Press', 2019, 1720, 'A mysterious shipwreck sets off an international chase.', 'Agents uncover a coded manifesto hidden in the debris.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (93, 'Glacier Pathways', 'Maple Leaf Press', 2022, 1460, 'A guide through the world''s most striking ice formations.', 'Safety tips, routes, and climate insights.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (94, 'Scribes of the Republic', 'Roma Books', 2015, 1920, 'Rome''s politics told through the eyes of ancient writers.', 'Stories of intrigue preserved on fragile scrolls.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (95, 'Twin Pagoda Pursuit', 'Sora Publishing', 2020, 1840, 'Two identical temples hide a long-lost treasure.', 'A chase across Japan tests loyalty and cunning.', 3, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (96, 'Songs of the Hollow Glen', 'Emerald House', 1989, 1170, 'Stories and legends from Ireland’s forgotten valleys.', 'Tales gathered from villagers, poets, and wanderers.', 4, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (97, 'Cold Protocol', 'Sterling Press', 2011, 1550, 'A rogue scientist releases encrypted demands.', 'Investigators race to prevent a biotechnical disaster.', 2, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (98, 'Skybound Guidebook', 'Maple Leaf Press', 2016, 1330, 'A practical manual for high-altitude travelers.', 'Survival strategies and breathtaking viewpoints.', 1, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (99, 'Banner of the North Legion', 'Roma Books', 2023, 2140, 'A Roman unit ventures into unknown northern lands.', 'Battles, diplomacy, and alliances shape their fate.', 5, 1);
INSERT INTO books (id, title, publisher, year, price, synopsis, content, author_id, admin_id) VALUES (100, 'Cranes Over Sendai', 'Sora Publishing', 2019, 1710, 'Origami cranes lead to clues in an unfolding mystery.', 'A journalist uncovers messages hidden in folded paper.', 3, 1);

-- Book genres
INSERT INTO book_genres (book_id, genre_id) VALUES (1, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (2, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (2, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (3, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (3, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (4, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (5, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (6, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (7, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (7, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (8, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (8, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (9, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (10, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (11, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (12, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (12, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (13, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (13, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (14, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (14, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (15, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (15, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (16, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (17, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (18, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (18, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (19, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (19, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (20, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (21, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (21, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (22, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (22, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (23, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (24, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (25, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (26, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (27, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (27, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (28, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (29, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (30, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (30, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (31, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (31, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (32, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (33, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (34, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (35, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (35, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (36, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (36, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (37, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (37, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (38, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (38, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (39, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (40, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (41, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (41, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (42, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (43, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (43, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (44, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (45, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (45, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (46, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (47, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (47, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (48, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (49, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (49, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (50, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (51, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (51, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (52, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (53, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (53, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (54, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (54, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (55, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (56, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (56, 3);
INSERT INTO book_genres (book_id, genre_id) VALUES (57, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (58, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (58, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (59, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (59, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (60, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (60, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (61, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (62, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (62, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (63, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (63, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (64, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (65, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (65, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (66, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (67, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (68, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (68, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (69, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (69, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (70, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (70, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (71, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (72, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (73, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (73, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (74, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (75, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (76, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (77, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (78, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (78, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (79, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (79, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (80, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (81, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (82, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (82, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (83, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (83, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (84, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (85, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (86, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (86, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (87, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (87, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (88, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (89, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (90, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (90, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (91, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (92, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (93, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (93, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (94, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (95, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (95, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (96, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (97, 5);
INSERT INTO book_genres (book_id, genre_id) VALUES (98, 2);
INSERT INTO book_genres (book_id, genre_id) VALUES (99, 1);
INSERT INTO book_genres (book_id, genre_id) VALUES (99, 4);
INSERT INTO book_genres (book_id, genre_id) VALUES (100, 5);

COMMIT;