START TRANSACTION;

INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (1, 5998, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (1, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 1);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (2, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 1);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (3, 1, 6, 1038, CURRENT_TIMESTAMP, 84, 1);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (4, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 1);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (2, 2831, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (5, 1, 9, 1314, CURRENT_TIMESTAMP, 93, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (6, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (7, 1, 1, 187, CURRENT_TIMESTAMP, 68, 2);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (3, 5904, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (8, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (9, 1, 3, 444, CURRENT_TIMESTAMP, 87, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (10, 1, 8, 1120, CURRENT_TIMESTAMP, 91, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (11, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (12, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 3);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (4, 4280, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (13, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (14, 1, 5, 930, CURRENT_TIMESTAMP, 77, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (15, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 4);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (5, 2646, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (16, 1, 4, 504, CURRENT_TIMESTAMP, 65, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (17, 1, 8, 1760, CURRENT_TIMESTAMP, 83, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (18, 1, 2, 382, CURRENT_TIMESTAMP, 69, 5);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (6, 6578, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (19, 1, 4, 476, CURRENT_TIMESTAMP, 90, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (20, 1, 4, 856, CURRENT_TIMESTAMP, 99, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (21, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (22, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (23, 1, 9, 1836, CURRENT_TIMESTAMP, 59, 6);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (7, 3848, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (24, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (25, 1, 4, 468, CURRENT_TIMESTAMP, 96, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (26, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 7);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (8, 3915, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (27, 1, 5, 820, CURRENT_TIMESTAMP, 76, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (28, 1, 2, 362, CURRENT_TIMESTAMP, 78, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (29, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (30, 1, 7, 1393, CURRENT_TIMESTAMP, 63, 8);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (9, 5876, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (31, 0, NULL, 1840, CURRENT_TIMESTAMP, 95, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (32, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (33, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (34, 1, 2, 222, CURRENT_TIMESTAMP, 75, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (35, 1, 8, 1264, CURRENT_TIMESTAMP, 62, 9);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (10, 4726, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (36, 0, NULL, 1570, CURRENT_TIMESTAMP, 66, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (37, 0, NULL, 1200, CURRENT_TIMESTAMP, 80, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (38, 1, 3, 486, CURRENT_TIMESTAMP, 74, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (39, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 10);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (11, 5920, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (40, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (41, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (42, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (43, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 11);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (12, 3399, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (44, 1, 1, 157, CURRENT_TIMESTAMP, 66, 12);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (45, 1, 4, 692, CURRENT_TIMESTAMP, 84, 12);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (46, 1, 6, 1224, CURRENT_TIMESTAMP, 59, 12);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (47, 1, 1, 186, CURRENT_TIMESTAMP, 77, 12);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (48, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 12);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (13, 4991, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (49, 0, NULL, 1840, CURRENT_TIMESTAMP, 95, 13);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (50, 0, NULL, 1810, CURRENT_TIMESTAMP, 78, 13);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (51, 1, 9, 1341, CURRENT_TIMESTAMP, 57, 13);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (14, 2546, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (52, 1, 1, 164, CURRENT_TIMESTAMP, 76, 14);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (53, 1, 6, 846, CURRENT_TIMESTAMP, 89, 14);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (54, 1, 8, 1536, CURRENT_TIMESTAMP, 94, 14);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (15, 2838, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (55, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 15);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (56, 1, 5, 630, CURRENT_TIMESTAMP, 65, 15);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (57, 1, 4, 588, CURRENT_TIMESTAMP, 81, 15);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (16, 6020, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (58, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 16);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (59, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 16);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (60, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 16);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (61, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 16);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (17, 5478, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (62, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 17);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (63, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 17);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (64, 1, 6, 948, CURRENT_TIMESTAMP, 62, 17);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (65, 1, 6, 1320, CURRENT_TIMESTAMP, 83, 17);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (18, 5423, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (66, 1, 1, 108, CURRENT_TIMESTAMP, 85, 18);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (67, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 18);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (68, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 18);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (69, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 18);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (70, 1, 5, 545, CURRENT_TIMESTAMP, 70, 18);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (19, 4933, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (71, 1, 7, 1309, CURRENT_TIMESTAMP, 68, 19);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (72, 1, 6, 840, CURRENT_TIMESTAMP, 91, 19);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (73, 1, 1, 214, CURRENT_TIMESTAMP, 99, 19);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (74, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 19);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (75, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 19);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (20, 4099, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (76, 1, 1, 199, CURRENT_TIMESTAMP, 63, 20);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (77, 0, NULL, 1910, CURRENT_TIMESTAMP, 69, 20);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (78, 1, 9, 1395, CURRENT_TIMESTAMP, 97, 20);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (79, 1, 5, 595, CURRENT_TIMESTAMP, 90, 20);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (21, 4691, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (80, 1, 5, 870, CURRENT_TIMESTAMP, 58, 21);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (81, 1, 7, 1281, CURRENT_TIMESTAMP, 60, 21);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (82, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 21);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (83, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 21);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (22, 7910, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (84, 1, 5, 880, CURRENT_TIMESTAMP, 73, 22);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (85, 0, NULL, 2040, CURRENT_TIMESTAMP, 59, 22);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (86, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 22);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (87, 0, NULL, 1990, CURRENT_TIMESTAMP, 63, 22);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (88, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 22);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (23, 5752, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (89, 1, 4, 528, CURRENT_TIMESTAMP, 64, 23);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (90, 1, 2, 374, CURRENT_TIMESTAMP, 68, 23);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (91, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 23);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (92, 0, NULL, 1200, CURRENT_TIMESTAMP, 80, 23);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (93, 0, NULL, 1730, CURRENT_TIMESTAMP, 84, 23);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (24, 2328, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (94, 1, 7, 882, CURRENT_TIMESTAMP, 65, 24);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (95, 1, 6, 876, CURRENT_TIMESTAMP, 93, 24);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (96, 1, 5, 570, CURRENT_TIMESTAMP, 61, 24);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (25, 5496, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (97, 1, 7, 756, CURRENT_TIMESTAMP, 85, 25);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (98, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 25);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (99, 0, NULL, 1570, CURRENT_TIMESTAMP, 66, 25);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (100, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 25);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (26, 5385, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (101, 1, 7, 1197, CURRENT_TIMESTAMP, 100, 26);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (102, 1, 6, 1086, CURRENT_TIMESTAMP, 78, 26);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (103, 1, 8, 1712, CURRENT_TIMESTAMP, 99, 26);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (104, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 26);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (27, 2574, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (105, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 27);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (106, 1, 2, 218, CURRENT_TIMESTAMP, 70, 27);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (107, 1, 4, 476, CURRENT_TIMESTAMP, 90, 27);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (28, 3565, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (108, 1, 2, 372, CURRENT_TIMESTAMP, 77, 28);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (109, 0, NULL, 1640, CURRENT_TIMESTAMP, 76, 28);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (110, 1, 6, 888, CURRENT_TIMESTAMP, 87, 28);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (111, 1, 5, 665, CURRENT_TIMESTAMP, 98, 28);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (29, 5618, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (112, 1, 7, 819, CURRENT_TIMESTAMP, 96, 29);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (113, 1, 9, 1269, CURRENT_TIMESTAMP, 89, 29);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (114, 0, NULL, 1400, CURRENT_TIMESTAMP, 91, 29);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (115, 1, 2, 440, CURRENT_TIMESTAMP, 83, 29);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (116, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 29);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (30, 2906, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (117, 0, NULL, 1580, CURRENT_TIMESTAMP, 62, 30);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (118, 1, 8, 1192, CURRENT_TIMESTAMP, 57, 30);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (119, 1, 1, 134, CURRENT_TIMESTAMP, 82, 30);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (31, 3114, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (120, 1, 1, 164, CURRENT_TIMESTAMP, 76, 31);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (121, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 31);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (122, 0, NULL, 1260, CURRENT_TIMESTAMP, 65, 31);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (32, 2748, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (123, 1, 3, 360, CURRENT_TIMESTAMP, 80, 32);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (124, 1, 4, 468, CURRENT_TIMESTAMP, 96, 32);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (125, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 32);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (33, 5144, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (126, 1, 8, 1192, CURRENT_TIMESTAMP, 57, 33);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (127, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 33);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (128, 0, NULL, 1190, CURRENT_TIMESTAMP, 90, 33);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (129, 1, 2, 292, CURRENT_TIMESTAMP, 93, 33);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (130, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 33);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (34, 5160, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (131, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 34);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (132, 0, NULL, 1990, CURRENT_TIMESTAMP, 63, 34);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (133, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 34);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (35, 4225, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (134, 1, 6, 1320, CURRENT_TIMESTAMP, 83, 35);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (135, 1, 1, 158, CURRENT_TIMESTAMP, 62, 35);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (136, 1, 7, 756, CURRENT_TIMESTAMP, 85, 35);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (137, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 35);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (138, 1, 1, 111, CURRENT_TIMESTAMP, 75, 35);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (36, 4356, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (139, 1, 6, 846, CURRENT_TIMESTAMP, 89, 36);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (140, 0, NULL, 1810, CURRENT_TIMESTAMP, 78, 36);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (141, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 36);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (37, 3018, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (142, 1, 4, 748, CURRENT_TIMESTAMP, 68, 37);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (143, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 37);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (144, 1, 5, 930, CURRENT_TIMESTAMP, 77, 37);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (38, 5590, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (145, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 38);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (146, 0, NULL, 2140, CURRENT_TIMESTAMP, 99, 38);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (147, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 38);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (39, 5036, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (148, 0, NULL, 1730, CURRENT_TIMESTAMP, 84, 39);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (149, 1, 9, 1836, CURRENT_TIMESTAMP, 59, 39);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (150, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 39);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (40, 890, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (151, 1, 1, 109, CURRENT_TIMESTAMP, 70, 40);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (152, 1, 3, 429, CURRENT_TIMESTAMP, 71, 40);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (153, 1, 2, 352, CURRENT_TIMESTAMP, 73, 40);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (41, 7557, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (154, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 41);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (155, 1, 7, 1337, CURRENT_TIMESTAMP, 69, 41);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (156, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 41);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (157, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 41);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (158, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 41);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (42, 5128, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (159, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 42);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (160, 1, 7, 896, CURRENT_TIMESTAMP, 67, 42);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (161, 1, 3, 642, CURRENT_TIMESTAMP, 99, 42);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (162, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 42);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (43, 5582, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (163, 1, 6, 702, CURRENT_TIMESTAMP, 96, 43);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (164, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 43);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (165, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 43);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (166, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 43);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (44, 4866, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (167, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 44);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (168, 1, 2, 266, CURRENT_TIMESTAMP, 98, 44);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (169, 1, 1, 220, CURRENT_TIMESTAMP, 83, 44);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (170, 1, 5, 850, CURRENT_TIMESTAMP, 88, 44);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (171, 0, NULL, 1840, CURRENT_TIMESTAMP, 95, 44);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (45, 4876, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (172, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 45);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (173, 0, NULL, 1990, CURRENT_TIMESTAMP, 63, 45);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (174, 1, 9, 1566, CURRENT_TIMESTAMP, 58, 45);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (46, 2885, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (175, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 46);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (176, 1, 8, 864, CURRENT_TIMESTAMP, 85, 46);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (177, 1, 3, 471, CURRENT_TIMESTAMP, 66, 46);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (47, 2735, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (178, 1, 5, 790, CURRENT_TIMESTAMP, 62, 47);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (179, 1, 4, 456, CURRENT_TIMESTAMP, 61, 47);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (180, 1, 4, 656, CURRENT_TIMESTAMP, 76, 47);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (181, 1, 7, 833, CURRENT_TIMESTAMP, 90, 47);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (48, 3696, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (182, 0, NULL, 1860, CURRENT_TIMESTAMP, 77, 48);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (183, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 48);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (184, 1, 1, 126, CURRENT_TIMESTAMP, 65, 48);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (49, 4566, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (185, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 49);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (186, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 49);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (187, 1, 4, 556, CURRENT_TIMESTAMP, 72, 49);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (188, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 49);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (50, 4867, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (189, 1, 9, 1080, CURRENT_TIMESTAMP, 80, 50);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (190, 0, NULL, 2040, CURRENT_TIMESTAMP, 59, 50);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (191, 1, 3, 438, CURRENT_TIMESTAMP, 93, 50);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (192, 1, 7, 1309, CURRENT_TIMESTAMP, 68, 50);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (51, 5216, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (193, 1, 3, 516, CURRENT_TIMESTAMP, 92, 51);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (194, 0, NULL, 1730, CURRENT_TIMESTAMP, 84, 51);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (195, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 51);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (196, 0, NULL, 1490, CURRENT_TIMESTAMP, 57, 51);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (52, 3500, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (197, 0, NULL, 1810, CURRENT_TIMESTAMP, 78, 52);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (198, 1, 2, 280, CURRENT_TIMESTAMP, 91, 52);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (199, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 52);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (53, 2703, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (200, 1, 8, 952, CURRENT_TIMESTAMP, 90, 53);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (201, 1, 7, 896, CURRENT_TIMESTAMP, 67, 53);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (202, 1, 5, 855, CURRENT_TIMESTAMP, 100, 53);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (54, 4034, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (203, 1, 4, 736, CURRENT_TIMESTAMP, 95, 54);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (204, 0, NULL, 2040, CURRENT_TIMESTAMP, 59, 54);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (205, 1, 2, 346, CURRENT_TIMESTAMP, 84, 54);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (206, 1, 8, 912, CURRENT_TIMESTAMP, 61, 54);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (55, 3030, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (207, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 55);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (208, 0, NULL, 1490, CURRENT_TIMESTAMP, 57, 55);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (209, 1, 1, 220, CURRENT_TIMESTAMP, 83, 55);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (56, 2356, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (210, 1, 4, 856, CURRENT_TIMESTAMP, 99, 56);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (211, 0, NULL, 1260, CURRENT_TIMESTAMP, 65, 56);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (212, 1, 2, 240, CURRENT_TIMESTAMP, 80, 56);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (57, 3473, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (213, 1, 4, 620, CURRENT_TIMESTAMP, 97, 57);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (214, 1, 7, 973, CURRENT_TIMESTAMP, 72, 57);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (215, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 57);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (58, 2762, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (216, 1, 5, 870, CURRENT_TIMESTAMP, 58, 58);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (217, 0, NULL, 1400, CURRENT_TIMESTAMP, 91, 58);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (218, 1, 3, 492, CURRENT_TIMESTAMP, 76, 58);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (59, 7299, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (219, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 59);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (220, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 59);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (221, 1, 7, 1029, CURRENT_TIMESTAMP, 81, 59);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (222, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 59);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (223, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 59);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (60, 7508, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (224, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 60);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (225, 0, NULL, 1870, CURRENT_TIMESTAMP, 68, 60);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (226, 1, 3, 558, CURRENT_TIMESTAMP, 77, 60);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (227, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 60);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (228, 0, NULL, 1990, CURRENT_TIMESTAMP, 63, 60);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (61, 3166, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (229, 1, 6, 876, CURRENT_TIMESTAMP, 93, 61);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (230, 1, 5, 860, CURRENT_TIMESTAMP, 92, 61);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (231, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 61);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (62, 4162, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (232, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 62);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (233, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 62);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (234, 1, 2, 382, CURRENT_TIMESTAMP, 69, 62);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (235, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 62);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (63, 5795, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (236, 1, 9, 972, CURRENT_TIMESTAMP, 85, 63);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (237, 1, 9, 1413, CURRENT_TIMESTAMP, 66, 63);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (238, 0, NULL, 1580, CURRENT_TIMESTAMP, 62, 63);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (239, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 63);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (64, 4740, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (240, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 64);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (241, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 64);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (242, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 64);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (65, 3659, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (243, 0, NULL, 1080, CURRENT_TIMESTAMP, 85, 65);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (244, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 65);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (245, 1, 1, 171, CURRENT_TIMESTAMP, 100, 65);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (246, 1, 6, 948, CURRENT_TIMESTAMP, 62, 65);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (66, 2910, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (247, 1, 6, 714, CURRENT_TIMESTAMP, 90, 66);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (248, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 66);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (249, 1, 4, 856, CURRENT_TIMESTAMP, 99, 66);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (67, 2583, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (250, 1, 2, 282, CURRENT_TIMESTAMP, 89, 67);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (251, 1, 2, 376, CURRENT_TIMESTAMP, 79, 67);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (252, 1, 5, 715, CURRENT_TIMESTAMP, 71, 67);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (253, 1, 5, 700, CURRENT_TIMESTAMP, 91, 67);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (254, 1, 3, 510, CURRENT_TIMESTAMP, 88, 67);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (68, 4968, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (255, 1, 1, 155, CURRENT_TIMESTAMP, 97, 68);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (256, 1, 8, 1632, CURRENT_TIMESTAMP, 59, 68);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (257, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 68);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (258, 1, 9, 1791, CURRENT_TIMESTAMP, 63, 68);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (69, 5550, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (259, 0, NULL, 1090, CURRENT_TIMESTAMP, 70, 69);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (260, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 69);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (261, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 69);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (262, 0, NULL, 1840, CURRENT_TIMESTAMP, 95, 69);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (70, 4890, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (263, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 70);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (264, 0, NULL, 1860, CURRENT_TIMESTAMP, 77, 70);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (265, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 70);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (71, 3540, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (266, 1, 6, 798, CURRENT_TIMESTAMP, 98, 71);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (267, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 71);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (268, 1, 6, 1122, CURRENT_TIMESTAMP, 68, 71);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (72, 3900, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (269, 1, 2, 362, CURRENT_TIMESTAMP, 78, 72);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (270, 1, 6, 1146, CURRENT_TIMESTAMP, 69, 72);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (271, 0, NULL, 1200, CURRENT_TIMESTAMP, 80, 72);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (272, 1, 8, 1192, CURRENT_TIMESTAMP, 57, 72);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (73, 6331, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (273, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 73);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (274, 1, 9, 1521, CURRENT_TIMESTAMP, 86, 73);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (275, 0, NULL, 1730, CURRENT_TIMESTAMP, 84, 73);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (276, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 73);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (74, 2028, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (277, 1, 6, 882, CURRENT_TIMESTAMP, 81, 74);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (278, 1, 3, 378, CURRENT_TIMESTAMP, 65, 74);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (279, 1, 5, 585, CURRENT_TIMESTAMP, 96, 74);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (280, 1, 1, 183, CURRENT_TIMESTAMP, 60, 74);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (75, 2704, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (281, 1, 7, 1029, CURRENT_TIMESTAMP, 81, 75);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (282, 1, 3, 384, CURRENT_TIMESTAMP, 67, 75);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (283, 1, 1, 157, CURRENT_TIMESTAMP, 66, 75);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (284, 1, 9, 1134, CURRENT_TIMESTAMP, 65, 75);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (76, 3577, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (285, 1, 3, 561, CURRENT_TIMESTAMP, 68, 76);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (286, 1, 8, 1360, CURRENT_TIMESTAMP, 88, 76);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (287, 1, 9, 1656, CURRENT_TIMESTAMP, 95, 76);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (77, 2143, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (288, 1, 6, 894, CURRENT_TIMESTAMP, 57, 77);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (289, 1, 5, 775, CURRENT_TIMESTAMP, 97, 77);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (290, 1, 3, 474, CURRENT_TIMESTAMP, 62, 77);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (78, 2898, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (291, 1, 8, 1128, CURRENT_TIMESTAMP, 89, 78);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (292, 1, 6, 1086, CURRENT_TIMESTAMP, 78, 78);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (293, 1, 6, 684, CURRENT_TIMESTAMP, 61, 78);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (79, 7900, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (294, 0, NULL, 1910, CURRENT_TIMESTAMP, 69, 79);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (295, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 79);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (296, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 79);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (297, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 79);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (298, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 79);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (80, 1979, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (299, 1, 4, 592, CURRENT_TIMESTAMP, 87, 80);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (300, 1, 5, 865, CURRENT_TIMESTAMP, 84, 80);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (301, 1, 3, 522, CURRENT_TIMESTAMP, 58, 80);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (81, 5065, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (302, 0, NULL, 2140, CURRENT_TIMESTAMP, 99, 81);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (303, 1, 3, 324, CURRENT_TIMESTAMP, 85, 81);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (304, 1, 7, 1281, CURRENT_TIMESTAMP, 60, 81);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (305, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 81);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (82, 5420, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (306, 0, NULL, 1860, CURRENT_TIMESTAMP, 77, 82);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (307, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 82);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (308, 1, 3, 420, CURRENT_TIMESTAMP, 91, 82);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (309, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 82);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (83, 4609, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (310, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 83);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (311, 1, 3, 597, CURRENT_TIMESTAMP, 63, 83);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (312, 1, 3, 360, CURRENT_TIMESTAMP, 80, 83);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (313, 1, 2, 222, CURRENT_TIMESTAMP, 75, 83);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (314, 0, NULL, 2040, CURRENT_TIMESTAMP, 59, 83);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (84, 6272, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (315, 0, NULL, 1640, CURRENT_TIMESTAMP, 76, 84);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (316, 0, NULL, 1190, CURRENT_TIMESTAMP, 90, 84);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (317, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 84);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (318, 1, 7, 1344, CURRENT_TIMESTAMP, 94, 84);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (319, 1, 2, 218, CURRENT_TIMESTAMP, 70, 84);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (85, 3660, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (320, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 85);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (321, 0, NULL, 2200, CURRENT_TIMESTAMP, 83, 85);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (86, 4454, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (322, 1, 9, 1260, CURRENT_TIMESTAMP, 91, 86);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (323, 1, 1, 214, CURRENT_TIMESTAMP, 99, 86);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (324, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 86);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (325, 0, NULL, 1840, CURRENT_TIMESTAMP, 95, 86);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (87, 3854, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (326, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 87);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (327, 0, NULL, 1260, CURRENT_TIMESTAMP, 65, 87);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (328, 1, 3, 576, CURRENT_TIMESTAMP, 94, 87);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (329, 1, 4, 588, CURRENT_TIMESTAMP, 81, 87);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (88, 2434, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (330, 1, 8, 864, CURRENT_TIMESTAMP, 85, 88);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (331, 1, 9, 1332, CURRENT_TIMESTAMP, 87, 88);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (332, 1, 2, 238, CURRENT_TIMESTAMP, 90, 88);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (89, 3405, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (333, 1, 9, 1476, CURRENT_TIMESTAMP, 76, 89);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (334, 1, 3, 471, CURRENT_TIMESTAMP, 66, 89);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (335, 1, 9, 1458, CURRENT_TIMESTAMP, 74, 89);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (90, 7870, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (336, 1, 4, 620, CURRENT_TIMESTAMP, 97, 90);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (337, 0, NULL, 1860, CURRENT_TIMESTAMP, 77, 90);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (338, 0, NULL, 1490, CURRENT_TIMESTAMP, 57, 90);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (339, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 90);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (340, 0, NULL, 2200, CURRENT_TIMESTAMP, 83, 90);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (91, 7575, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (341, 1, 8, 1368, CURRENT_TIMESTAMP, 100, 91);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (342, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 91);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (343, 1, 9, 1647, CURRENT_TIMESTAMP, 60, 91);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (344, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 91);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (345, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 91);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (92, 5857, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (346, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 92);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (347, 1, 2, 352, CURRENT_TIMESTAMP, 73, 92);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (348, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 92);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (349, 1, 5, 865, CURRENT_TIMESTAMP, 84, 92);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (350, 0, NULL, 1910, CURRENT_TIMESTAMP, 69, 92);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (93, 4663, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (351, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 93);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (352, 1, 9, 981, CURRENT_TIMESTAMP, 70, 93);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (353, 1, 6, 768, CURRENT_TIMESTAMP, 67, 93);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (354, 1, 6, 1194, CURRENT_TIMESTAMP, 63, 93);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (94, 4991, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (355, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 94);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (356, 0, NULL, 1810, CURRENT_TIMESTAMP, 78, 94);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (357, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 94);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (358, 1, 1, 111, CURRENT_TIMESTAMP, 75, 94);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (95, 4328, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (359, 0, NULL, 1260, CURRENT_TIMESTAMP, 65, 95);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (360, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 95);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (361, 1, 9, 972, CURRENT_TIMESTAMP, 85, 95);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (362, 1, 2, 376, CURRENT_TIMESTAMP, 79, 95);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (96, 4610, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (363, 1, 8, 1192, CURRENT_TIMESTAMP, 57, 96);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (364, 1, 2, 218, CURRENT_TIMESTAMP, 70, 96);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (365, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 96);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (366, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 96);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (97, 5322, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (367, 1, 1, 120, CURRENT_TIMESTAMP, 80, 97);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (368, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 97);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (369, 1, 8, 1352, CURRENT_TIMESTAMP, 86, 97);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (370, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 97);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (371, 0, NULL, 1570, CURRENT_TIMESTAMP, 66, 97);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (98, 4362, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (372, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 98);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (373, 1, 8, 1472, CURRENT_TIMESTAMP, 95, 98);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (374, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 98);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (99, 1891, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (375, 1, 1, 183, CURRENT_TIMESTAMP, 60, 99);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (376, 1, 8, 1360, CURRENT_TIMESTAMP, 88, 99);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (377, 1, 2, 348, CURRENT_TIMESTAMP, 58, 99);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (100, 8180, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (378, 0, NULL, 2140, CURRENT_TIMESTAMP, 99, 100);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (379, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 100);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (380, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 100);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (381, 0, NULL, 1730, CURRENT_TIMESTAMP, 84, 100);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (382, 0, NULL, 1580, CURRENT_TIMESTAMP, 62, 100);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (101, 5750, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (383, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 101);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (384, 1, 4, 588, CURRENT_TIMESTAMP, 81, 101);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (385, 0, NULL, 1810, CURRENT_TIMESTAMP, 78, 101);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (386, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 101);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (387, 1, 1, 162, CURRENT_TIMESTAMP, 74, 101);

COMMIT;