START TRANSACTION;

INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (1, 1340, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (1, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 1);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (2, 1330, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (2, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 2);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (3, 1536, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (3, 1, 8, 1536, CURRENT_TIMESTAMP, 94, 3);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (4, 398, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (4, 1, 2, 398, CURRENT_TIMESTAMP, 63, 4);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (5, 1720, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (5, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 5);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (6, 510, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (6, 1, 3, 510, CURRENT_TIMESTAMP, 88, 6);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (7, 1170, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (7, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 7);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (8, 740, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (8, 1, 5, 740, CURRENT_TIMESTAMP, 87, 8);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (9, 1880, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (9, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 9);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (10, 1620, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (10, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 10);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (11, 1410, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (11, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 11);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (12, 1760, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (12, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 12);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (13, 1146, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (13, 1, 6, 1146, CURRENT_TIMESTAMP, 69, 13);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (14, 1860, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (14, 0, NULL, 1860, CURRENT_TIMESTAMP, 77, 14);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (15, 1480, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (15, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 15);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (16, 1830, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (16, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 16);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (17, 2200, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (17, 0, NULL, 2200, CURRENT_TIMESTAMP, 83, 17);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (18, 1140, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (18, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 18);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (19, 1740, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (19, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 19);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (20, 402, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (20, 1, 3, 402, CURRENT_TIMESTAMP, 82, 20);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (21, 1071, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (21, 1, 9, 1071, CURRENT_TIMESTAMP, 90, 21);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (22, 2140, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (22, 0, NULL, 2140, CURRENT_TIMESTAMP, 99, 22);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (23, 1480, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (23, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 23);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (24, 1309, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (24, 1, 7, 1309, CURRENT_TIMESTAMP, 68, 24);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (25, 1260, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (25, 1, 9, 1260, CURRENT_TIMESTAMP, 91, 25);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (26, 1320, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (26, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 26);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (27, 423, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (27, 1, 3, 423, CURRENT_TIMESTAMP, 89, 27);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (28, 1090, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (28, 0, NULL, 1090, CURRENT_TIMESTAMP, 70, 28);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (29, 1280, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (29, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 29);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (30, 126, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (30, 1, 1, 126, CURRENT_TIMESTAMP, 65, 30);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (31, 2200, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (31, 0, NULL, 2200, CURRENT_TIMESTAMP, 83, 31);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (32, 1683, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (32, 1, 9, 1683, CURRENT_TIMESTAMP, 68, 32);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (33, 1260, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (33, 0, NULL, 1260, CURRENT_TIMESTAMP, 65, 33);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (34, 1810, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (34, 0, NULL, 1810, CURRENT_TIMESTAMP, 78, 34);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (35, 1330, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (35, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 35);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (36, 1024, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (36, 1, 8, 1024, CURRENT_TIMESTAMP, 67, 36);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (37, 1880, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (37, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 37);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (38, 1330, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (38, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 38);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (39, 441, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (39, 1, 3, 441, CURRENT_TIMESTAMP, 81, 39);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (40, 1910, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (40, 0, NULL, 1910, CURRENT_TIMESTAMP, 69, 40);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (41, 492, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (41, 1, 3, 492, CURRENT_TIMESTAMP, 76, 41);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (42, 833, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (42, 1, 7, 833, CURRENT_TIMESTAMP, 90, 42);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (43, 1232, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (43, 1, 7, 1232, CURRENT_TIMESTAMP, 73, 43);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (44, 840, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (44, 1, 7, 840, CURRENT_TIMESTAMP, 80, 44);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (45, 1038, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (45, 1, 6, 1038, CURRENT_TIMESTAMP, 84, 45);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (46, 1224, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (46, 1, 6, 1224, CURRENT_TIMESTAMP, 59, 46);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (47, 1710, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (47, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 47);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (48, 973, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (48, 1, 7, 973, CURRENT_TIMESTAMP, 72, 48);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (49, 1428, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (49, 1, 7, 1428, CURRENT_TIMESTAMP, 59, 49);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (50, 328, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (50, 1, 2, 328, CURRENT_TIMESTAMP, 76, 50);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (51, 597, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (51, 1, 3, 597, CURRENT_TIMESTAMP, 63, 51);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (52, 1200, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (52, 0, NULL, 1200, CURRENT_TIMESTAMP, 80, 52);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (53, 1730, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (53, 0, NULL, 1730, CURRENT_TIMESTAMP, 84, 53);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (54, 120, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (54, 1, 1, 120, CURRENT_TIMESTAMP, 80, 54);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (55, 1080, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (55, 0, NULL, 1080, CURRENT_TIMESTAMP, 85, 55);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (56, 1910, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (56, 0, NULL, 1910, CURRENT_TIMESTAMP, 69, 56);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (57, 1690, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (57, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 57);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (58, 1760, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (58, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 58);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (59, 351, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (59, 1, 3, 351, CURRENT_TIMESTAMP, 96, 59);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (60, 1990, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (60, 0, NULL, 1990, CURRENT_TIMESTAMP, 63, 60);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (61, 1647, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (61, 1, 9, 1647, CURRENT_TIMESTAMP, 60, 61);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (62, 1550, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (62, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 62);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (63, 1760, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (63, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 63);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (64, 1690, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (64, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 64);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (65, 1090, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (65, 0, NULL, 1090, CURRENT_TIMESTAMP, 70, 65);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (66, 1080, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (66, 0, NULL, 1080, CURRENT_TIMESTAMP, 85, 66);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (67, 199, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (67, 1, 1, 199, CURRENT_TIMESTAMP, 63, 67);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (68, 558, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (68, 1, 3, 558, CURRENT_TIMESTAMP, 77, 68);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (69, 128, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (69, 1, 1, 128, CURRENT_TIMESTAMP, 67, 69);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (70, 1830, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (70, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 70);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (71, 1320, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (71, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 71);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (72, 1309, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (72, 1, 7, 1309, CURRENT_TIMESTAMP, 68, 72);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (73, 1920, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (73, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 73);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (74, 1690, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (74, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 74);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (75, 1218, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (75, 1, 7, 1218, CURRENT_TIMESTAMP, 58, 75);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (76, 146, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (76, 1, 1, 146, CURRENT_TIMESTAMP, 93, 76);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (77, 1422, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (77, 1, 9, 1422, CURRENT_TIMESTAMP, 62, 77);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (78, 1086, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (78, 1, 6, 1086, CURRENT_TIMESTAMP, 78, 78);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (79, 1700, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (79, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 79);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (80, 340, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (80, 1, 2, 340, CURRENT_TIMESTAMP, 88, 80);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (81, 1430, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (81, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 81);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (82, 1490, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (82, 0, NULL, 1490, CURRENT_TIMESTAMP, 57, 82);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (83, 1692, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (83, 1, 9, 1692, CURRENT_TIMESTAMP, 79, 83);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (84, 1190, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (84, 0, NULL, 1190, CURRENT_TIMESTAMP, 90, 84);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (85, 176, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (85, 1, 1, 176, CURRENT_TIMESTAMP, 73, 85);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (86, 1920, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (86, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 86);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (87, 2140, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (87, 0, NULL, 2140, CURRENT_TIMESTAMP, 99, 87);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (88, 1170, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (88, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 88);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (89, 561, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (89, 1, 3, 561, CURRENT_TIMESTAMP, 68, 89);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (90, 1870, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (90, 0, NULL, 1870, CURRENT_TIMESTAMP, 68, 90);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (91, 1140, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (91, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 91);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (92, 1260, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (92, 0, NULL, 1260, CURRENT_TIMESTAMP, 65, 92);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (93, 1910, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (93, 0, NULL, 1910, CURRENT_TIMESTAMP, 69, 93);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (94, 1086, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (94, 1, 6, 1086, CURRENT_TIMESTAMP, 78, 94);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (95, 666, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (95, 1, 6, 666, CURRENT_TIMESTAMP, 75, 95);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (96, 316, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (96, 1, 2, 316, CURRENT_TIMESTAMP, 62, 96);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (97, 1720, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (97, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 97);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (98, 973, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (98, 1, 7, 973, CURRENT_TIMESTAMP, 72, 98);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (99, 216, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (99, 1, 2, 216, CURRENT_TIMESTAMP, 85, 99);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (100, 654, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (100, 1, 6, 654, CURRENT_TIMESTAMP, 70, 100);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (101, 1110, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (101, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 101);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (102, 1428, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (102, 1, 7, 1428, CURRENT_TIMESTAMP, 59, 102);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (103, 513, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (103, 1, 3, 513, CURRENT_TIMESTAMP, 100, 103);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (104, 1080, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (104, 0, NULL, 1080, CURRENT_TIMESTAMP, 85, 104);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (105, 1710, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (105, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 105);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (106, 408, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (106, 1, 2, 408, CURRENT_TIMESTAMP, 59, 106);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (107, 1410, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (107, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 107);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (108, 1390, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (108, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 108);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (109, 1719, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (109, 1, 9, 1719, CURRENT_TIMESTAMP, 69, 109);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (110, 1570, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (110, 0, NULL, 1570, CURRENT_TIMESTAMP, 66, 110);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (111, 1720, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (111, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 111);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (112, 1410, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (112, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 112);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (113, 1740, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (113, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 113);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (114, 1830, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (114, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 114);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (115, 1710, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (115, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 115);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (116, 1498, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (116, 1, 7, 1498, CURRENT_TIMESTAMP, 99, 116);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (117, 543, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (117, 1, 3, 543, CURRENT_TIMESTAMP, 78, 117);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (118, 1840, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (118, 0, NULL, 1840, CURRENT_TIMESTAMP, 95, 118);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (119, 1620, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (119, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 119);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (120, 447, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (120, 1, 3, 447, CURRENT_TIMESTAMP, 57, 120);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (121, 2200, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (121, 0, NULL, 2200, CURRENT_TIMESTAMP, 83, 121);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (122, 1384, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (122, 1, 8, 1384, CURRENT_TIMESTAMP, 84, 122);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (123, 1392, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (123, 1, 8, 1392, CURRENT_TIMESTAMP, 58, 123);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (124, 134, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (124, 1, 1, 134, CURRENT_TIMESTAMP, 82, 124);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (125, 1557, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (125, 1, 9, 1557, CURRENT_TIMESTAMP, 84, 125);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (126, 1580, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (126, 0, NULL, 1580, CURRENT_TIMESTAMP, 62, 126);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (127, 785, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (127, 1, 5, 785, CURRENT_TIMESTAMP, 66, 127);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (128, 240, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (128, 1, 2, 240, CURRENT_TIMESTAMP, 80, 128);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (129, 378, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (129, 1, 3, 378, CURRENT_TIMESTAMP, 65, 129);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (130, 1990, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (130, 0, NULL, 1990, CURRENT_TIMESTAMP, 63, 130);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (131, 1038, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (131, 1, 6, 1038, CURRENT_TIMESTAMP, 84, 131);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (132, 1448, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (132, 1, 8, 1448, CURRENT_TIMESTAMP, 78, 132);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (133, 1632, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (133, 1, 8, 1632, CURRENT_TIMESTAMP, 59, 133);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (134, 1480, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (134, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 134);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (135, 1460, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (135, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 135);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (136, 1340, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (136, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 136);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (137, 1550, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (137, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 137);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (138, 1320, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (138, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 138);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (139, 576, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (139, 1, 3, 576, CURRENT_TIMESTAMP, 94, 139);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (140, 1700, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (140, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 140);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (141, 1080, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (141, 0, NULL, 1080, CURRENT_TIMESTAMP, 85, 141);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (142, 1480, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (142, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 142);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (143, 1920, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (143, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 143);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (144, 785, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (144, 1, 5, 785, CURRENT_TIMESTAMP, 66, 144);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (145, 1390, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (145, 0, NULL, 1390, CURRENT_TIMESTAMP, 72, 145);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (146, 1287, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (146, 1, 9, 1287, CURRENT_TIMESTAMP, 71, 146);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (147, 1190, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (147, 0, NULL, 1190, CURRENT_TIMESTAMP, 90, 147);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (148, 810, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (148, 1, 5, 810, CURRENT_TIMESTAMP, 74, 148);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (149, 1760, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (149, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 149);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (150, 1550, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (150, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 150);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (151, 1284, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (151, 1, 6, 1284, CURRENT_TIMESTAMP, 99, 151);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (152, 872, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (152, 1, 8, 872, CURRENT_TIMESTAMP, 70, 152);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (153, 1920, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (153, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 153);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (154, 1580, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (154, 0, NULL, 1580, CURRENT_TIMESTAMP, 62, 154);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (155, 1080, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (155, 0, NULL, 1080, CURRENT_TIMESTAMP, 85, 155);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (156, 552, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (156, 1, 3, 552, CURRENT_TIMESTAMP, 95, 156);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (157, 143, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (157, 1, 1, 143, CURRENT_TIMESTAMP, 71, 157);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (158, 1110, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (158, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 158);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (159, 1302, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (159, 1, 7, 1302, CURRENT_TIMESTAMP, 77, 159);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (160, 1470, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (160, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 160);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (161, 282, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (161, 1, 2, 282, CURRENT_TIMESTAMP, 89, 161);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (162, 1548, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (162, 1, 9, 1548, CURRENT_TIMESTAMP, 92, 162);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (163, 1620, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (163, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 163);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (164, 752, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (164, 1, 4, 752, CURRENT_TIMESTAMP, 79, 164);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (165, 1870, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (165, 0, NULL, 1870, CURRENT_TIMESTAMP, 68, 165);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (166, 1810, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (166, 0, NULL, 1810, CURRENT_TIMESTAMP, 78, 166);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (167, 785, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (167, 1, 5, 785, CURRENT_TIMESTAMP, 66, 167);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (168, 1340, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (168, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 168);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (169, 2200, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (169, 0, NULL, 2200, CURRENT_TIMESTAMP, 83, 169);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (170, 1170, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (170, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 170);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (171, 1710, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (171, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 171);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (172, 1570, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (172, 0, NULL, 1570, CURRENT_TIMESTAMP, 66, 172);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (173, 1099, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (173, 1, 7, 1099, CURRENT_TIMESTAMP, 66, 173);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (174, 1288, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (174, 1, 7, 1288, CURRENT_TIMESTAMP, 95, 174);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (175, 585, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (175, 1, 5, 585, CURRENT_TIMESTAMP, 96, 175);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (176, 1550, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (176, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 176);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (177, 2040, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (177, 0, NULL, 2040, CURRENT_TIMESTAMP, 59, 177);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (178, 833, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (178, 1, 7, 833, CURRENT_TIMESTAMP, 90, 178);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (179, 960, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (179, 1, 5, 960, CURRENT_TIMESTAMP, 94, 179);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (180, 1400, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (180, 0, NULL, 1400, CURRENT_TIMESTAMP, 91, 180);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (181, 1400, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (181, 0, NULL, 1400, CURRENT_TIMESTAMP, 91, 181);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (182, 133, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (182, 1, 1, 133, CURRENT_TIMESTAMP, 98, 182);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (183, 399, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (183, 1, 3, 399, CURRENT_TIMESTAMP, 98, 183);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (184, 1830, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (184, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 184);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (185, 1539, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (185, 1, 9, 1539, CURRENT_TIMESTAMP, 100, 185);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (186, 417, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (186, 1, 3, 417, CURRENT_TIMESTAMP, 72, 186);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (187, 1134, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (187, 1, 9, 1134, CURRENT_TIMESTAMP, 65, 187);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (188, 1260, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (188, 0, NULL, 1260, CURRENT_TIMESTAMP, 65, 188);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (189, 1620, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (189, 0, NULL, 1620, CURRENT_TIMESTAMP, 74, 189);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (190, 1570, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (190, 0, NULL, 1570, CURRENT_TIMESTAMP, 66, 190);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (191, 1170, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (191, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 191);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (192, 1460, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (192, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 192);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (193, 222, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (193, 1, 2, 222, CURRENT_TIMESTAMP, 75, 193);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (194, 1521, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (194, 1, 9, 1521, CURRENT_TIMESTAMP, 86, 194);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (195, 1710, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (195, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 195);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (196, 1170, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (196, 0, NULL, 1170, CURRENT_TIMESTAMP, 96, 196);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (197, 1100, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (197, 1, 5, 1100, CURRENT_TIMESTAMP, 83, 197);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (198, 1550, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (198, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 198);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (199, 1860, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (199, 0, NULL, 1860, CURRENT_TIMESTAMP, 77, 199);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (200, 372, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (200, 1, 2, 372, CURRENT_TIMESTAMP, 77, 200);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (201, 1710, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (201, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 201);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (202, 1260, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (202, 0, NULL, 1260, CURRENT_TIMESTAMP, 65, 202);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (203, 480, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (203, 1, 4, 480, CURRENT_TIMESTAMP, 80, 203);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (204, 973, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (204, 1, 7, 973, CURRENT_TIMESTAMP, 72, 204);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (205, 816, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (205, 1, 4, 816, CURRENT_TIMESTAMP, 59, 205);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (206, 1024, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (206, 1, 8, 1024, CURRENT_TIMESTAMP, 67, 206);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (207, 1200, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (207, 0, NULL, 1200, CURRENT_TIMESTAMP, 80, 207);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (208, 1490, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (208, 0, NULL, 1490, CURRENT_TIMESTAMP, 57, 208);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (209, 1460, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (209, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 209);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (210, 1410, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (210, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 210);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (211, 316, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (211, 1, 2, 316, CURRENT_TIMESTAMP, 62, 211);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (212, 1690, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (212, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 212);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (213, 840, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (213, 1, 6, 840, CURRENT_TIMESTAMP, 91, 213);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (214, 1014, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (214, 1, 6, 1014, CURRENT_TIMESTAMP, 86, 214);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (215, 834, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (215, 1, 6, 834, CURRENT_TIMESTAMP, 72, 215);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (216, 1480, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (216, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 216);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (217, 2040, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (217, 0, NULL, 2040, CURRENT_TIMESTAMP, 59, 217);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (218, 860, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (218, 1, 5, 860, CURRENT_TIMESTAMP, 92, 218);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (219, 382, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (219, 1, 2, 382, CURRENT_TIMESTAMP, 69, 219);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (220, 1640, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (220, 0, NULL, 1640, CURRENT_TIMESTAMP, 76, 220);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (221, 2140, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (221, 0, NULL, 2140, CURRENT_TIMESTAMP, 99, 221);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (222, 1860, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (222, 0, NULL, 1860, CURRENT_TIMESTAMP, 77, 222);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (223, 1330, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (223, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 223);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (224, 348, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (224, 1, 2, 348, CURRENT_TIMESTAMP, 58, 224);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (225, 1280, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (225, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 225);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (226, 1470, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (226, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 226);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (227, 1910, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (227, 0, NULL, 1910, CURRENT_TIMESTAMP, 69, 227);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (228, 872, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (228, 1, 8, 872, CURRENT_TIMESTAMP, 70, 228);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (229, 1476, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (229, 1, 9, 1476, CURRENT_TIMESTAMP, 76, 229);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (230, 429, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (230, 1, 3, 429, CURRENT_TIMESTAMP, 71, 230);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (231, 1090, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (231, 0, NULL, 1090, CURRENT_TIMESTAMP, 70, 231);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (232, 1116, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (232, 1, 6, 1116, CURRENT_TIMESTAMP, 77, 232);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (233, 384, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (233, 1, 2, 384, CURRENT_TIMESTAMP, 94, 233);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (234, 1488, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (234, 1, 8, 1488, CURRENT_TIMESTAMP, 77, 234);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (235, 752, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (235, 1, 4, 752, CURRENT_TIMESTAMP, 79, 235);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (236, 1740, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (236, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 236);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (237, 1140, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (237, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 237);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (238, 1022, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (238, 1, 7, 1022, CURRENT_TIMESTAMP, 93, 238);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (239, 585, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (239, 1, 5, 585, CURRENT_TIMESTAMP, 96, 239);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (240, 1341, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (240, 1, 9, 1341, CURRENT_TIMESTAMP, 57, 240);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (241, 1430, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (241, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 241);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (242, 1140, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (242, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 242);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (243, 695, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (243, 1, 5, 695, CURRENT_TIMESTAMP, 72, 243);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (244, 536, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (244, 1, 4, 536, CURRENT_TIMESTAMP, 82, 244);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (245, 856, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (245, 1, 4, 856, CURRENT_TIMESTAMP, 99, 245);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (246, 1280, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (246, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 246);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (247, 1200, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (247, 0, NULL, 1200, CURRENT_TIMESTAMP, 80, 247);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (248, 1330, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (248, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 248);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (249, 1498, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (249, 1, 7, 1498, CURRENT_TIMESTAMP, 99, 249);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (250, 1260, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (250, 1, 9, 1260, CURRENT_TIMESTAMP, 91, 250);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (251, 648, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (251, 1, 6, 648, CURRENT_TIMESTAMP, 85, 251);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (252, 1647, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (252, 1, 9, 1647, CURRENT_TIMESTAMP, 60, 252);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (253, 1448, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (253, 1, 8, 1448, CURRENT_TIMESTAMP, 78, 253);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (254, 155, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (254, 1, 1, 155, CURRENT_TIMESTAMP, 97, 254);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (255, 1314, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (255, 1, 9, 1314, CURRENT_TIMESTAMP, 93, 255);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (256, 120, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (256, 1, 1, 120, CURRENT_TIMESTAMP, 80, 256);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (257, 1400, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (257, 0, NULL, 1400, CURRENT_TIMESTAMP, 91, 257);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (258, 176, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (258, 1, 1, 176, CURRENT_TIMESTAMP, 73, 258);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (259, 700, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (259, 1, 5, 700, CURRENT_TIMESTAMP, 91, 259);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (260, 1490, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (260, 0, NULL, 1490, CURRENT_TIMESTAMP, 57, 260);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (261, 1410, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (261, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 261);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (262, 1218, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (262, 1, 7, 1218, CURRENT_TIMESTAMP, 58, 262);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (263, 1870, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (263, 0, NULL, 1870, CURRENT_TIMESTAMP, 68, 263);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (264, 714, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (264, 1, 6, 714, CURRENT_TIMESTAMP, 90, 264);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (265, 1430, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (265, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 265);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (266, 1422, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (266, 1, 9, 1422, CURRENT_TIMESTAMP, 62, 266);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (267, 1393, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (267, 1, 7, 1393, CURRENT_TIMESTAMP, 63, 267);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (268, 1410, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (268, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 268);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (269, 912, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (269, 1, 8, 912, CURRENT_TIMESTAMP, 61, 269);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (270, 1400, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (270, 0, NULL, 1400, CURRENT_TIMESTAMP, 91, 270);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (271, 1920, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (271, 0, NULL, 1920, CURRENT_TIMESTAMP, 94, 271);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (272, 2200, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (272, 0, NULL, 2200, CURRENT_TIMESTAMP, 83, 272);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (273, 183, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (273, 1, 1, 183, CURRENT_TIMESTAMP, 60, 273);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (274, 1580, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (274, 0, NULL, 1580, CURRENT_TIMESTAMP, 62, 274);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (275, 346, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (275, 1, 2, 346, CURRENT_TIMESTAMP, 84, 275);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (276, 513, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (276, 1, 3, 513, CURRENT_TIMESTAMP, 100, 276);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (277, 1470, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (277, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 277);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (278, 1870, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (278, 0, NULL, 1870, CURRENT_TIMESTAMP, 68, 278);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (279, 278, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (279, 1, 2, 278, CURRENT_TIMESTAMP, 72, 279);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (280, 1570, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (280, 0, NULL, 1570, CURRENT_TIMESTAMP, 66, 280);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (281, 972, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (281, 1, 6, 972, CURRENT_TIMESTAMP, 74, 281);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (282, 1410, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (282, 0, NULL, 1410, CURRENT_TIMESTAMP, 89, 282);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (283, 1710, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (283, 0, NULL, 1710, CURRENT_TIMESTAMP, 100, 283);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (284, 1152, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (284, 1, 9, 1152, CURRENT_TIMESTAMP, 67, 284);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (285, 1192, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (285, 1, 8, 1192, CURRENT_TIMESTAMP, 57, 285);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (286, 2040, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (286, 0, NULL, 2040, CURRENT_TIMESTAMP, 59, 286);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (287, 1490, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (287, 0, NULL, 1490, CURRENT_TIMESTAMP, 57, 287);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (288, 1640, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (288, 0, NULL, 1640, CURRENT_TIMESTAMP, 76, 288);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (289, 1470, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (289, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 289);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (290, 1550, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (290, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 290);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (291, 173, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (291, 1, 1, 173, CURRENT_TIMESTAMP, 84, 291);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (292, 1038, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (292, 1, 6, 1038, CURRENT_TIMESTAMP, 84, 292);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (293, 856, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (293, 1, 4, 856, CURRENT_TIMESTAMP, 99, 293);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (294, 368, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (294, 1, 2, 368, CURRENT_TIMESTAMP, 95, 294);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (295, 1320, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (295, 1, 6, 1320, CURRENT_TIMESTAMP, 83, 295);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (296, 1480, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (296, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 296);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (297, 1320, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (297, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 297);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (298, 1320, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (298, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 298);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (299, 882, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (299, 1, 7, 882, CURRENT_TIMESTAMP, 65, 299);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (300, 148, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (300, 1, 1, 148, CURRENT_TIMESTAMP, 87, 300);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (301, 264, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (301, 1, 2, 264, CURRENT_TIMESTAMP, 64, 301);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (302, 1580, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (302, 0, NULL, 1580, CURRENT_TIMESTAMP, 62, 302);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (303, 804, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (303, 1, 6, 804, CURRENT_TIMESTAMP, 82, 303);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (304, 1700, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (304, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 304);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (305, 1110, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (305, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 305);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (306, 1460, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (306, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 306);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (307, 1880, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (307, 0, NULL, 1880, CURRENT_TIMESTAMP, 79, 307);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (308, 1330, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (308, 0, NULL, 1330, CURRENT_TIMESTAMP, 98, 308);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (309, 1566, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (309, 1, 9, 1566, CURRENT_TIMESTAMP, 58, 309);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (310, 146, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (310, 1, 1, 146, CURRENT_TIMESTAMP, 93, 310);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (311, 705, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (311, 1, 5, 705, CURRENT_TIMESTAMP, 89, 311);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (312, 1700, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (312, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 312);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (313, 1430, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (313, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 313);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (314, 1144, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (314, 1, 8, 1144, CURRENT_TIMESTAMP, 71, 314);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (315, 1690, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (315, 0, NULL, 1690, CURRENT_TIMESTAMP, 86, 315);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (316, 188, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (316, 1, 1, 188, CURRENT_TIMESTAMP, 79, 316);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (317, 768, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (317, 1, 4, 768, CURRENT_TIMESTAMP, 94, 317);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (318, 1280, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (318, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 318);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (319, 199, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (319, 1, 1, 199, CURRENT_TIMESTAMP, 63, 319);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (320, 2200, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (320, 0, NULL, 2200, CURRENT_TIMESTAMP, 83, 320);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (321, 366, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (321, 1, 2, 366, CURRENT_TIMESTAMP, 60, 321);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (322, 228, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (322, 1, 2, 228, CURRENT_TIMESTAMP, 61, 322);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (323, 1490, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (323, 0, NULL, 1490, CURRENT_TIMESTAMP, 57, 323);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (324, 1080, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (324, 0, NULL, 1080, CURRENT_TIMESTAMP, 85, 324);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (325, 1053, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (325, 1, 9, 1053, CURRENT_TIMESTAMP, 96, 325);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (326, 1280, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (326, 0, NULL, 1280, CURRENT_TIMESTAMP, 67, 326);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (327, 1910, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (327, 0, NULL, 1910, CURRENT_TIMESTAMP, 69, 327);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (328, 1472, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (328, 1, 8, 1472, CURRENT_TIMESTAMP, 95, 328);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (329, 1470, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (329, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 329);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (330, 1840, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (330, 0, NULL, 1840, CURRENT_TIMESTAMP, 95, 330);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (331, 777, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (331, 1, 7, 777, CURRENT_TIMESTAMP, 75, 331);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (332, 1110, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (332, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 332);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (333, 1548, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (333, 1, 9, 1548, CURRENT_TIMESTAMP, 92, 333);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (334, 1190, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (334, 0, NULL, 1190, CURRENT_TIMESTAMP, 90, 334);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (335, 510, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (335, 1, 3, 510, CURRENT_TIMESTAMP, 88, 335);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (336, 558, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (336, 1, 3, 558, CURRENT_TIMESTAMP, 77, 336);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (337, 1860, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (337, 0, NULL, 1860, CURRENT_TIMESTAMP, 77, 337);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (338, 972, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (338, 1, 6, 972, CURRENT_TIMESTAMP, 74, 338);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (339, 1340, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (339, 0, NULL, 1340, CURRENT_TIMESTAMP, 82, 339);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (340, 724, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (340, 1, 4, 724, CURRENT_TIMESTAMP, 78, 340);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (341, 164, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (341, 1, 1, 164, CURRENT_TIMESTAMP, 76, 341);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (342, 1720, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (342, 0, NULL, 1720, CURRENT_TIMESTAMP, 92, 342);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (343, 1190, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (343, 0, NULL, 1190, CURRENT_TIMESTAMP, 90, 343);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (344, 342, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (344, 1, 3, 342, CURRENT_TIMESTAMP, 61, 344);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (345, 1460, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (345, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 345);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (346, 1470, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (346, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 346);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (347, 1730, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (347, 0, NULL, 1730, CURRENT_TIMESTAMP, 84, 347);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (348, 376, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (348, 1, 2, 376, CURRENT_TIMESTAMP, 79, 348);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (349, 444, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (349, 1, 4, 444, CURRENT_TIMESTAMP, 75, 349);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (350, 1192, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (350, 1, 8, 1192, CURRENT_TIMESTAMP, 57, 350);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (351, 1044, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (351, 1, 6, 1044, CURRENT_TIMESTAMP, 58, 351);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (352, 1480, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (352, 0, NULL, 1480, CURRENT_TIMESTAMP, 87, 352);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (353, 252, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (353, 1, 2, 252, CURRENT_TIMESTAMP, 65, 353);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (354, 1460, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (354, 0, NULL, 1460, CURRENT_TIMESTAMP, 93, 354);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (355, 1024, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (355, 1, 8, 1024, CURRENT_TIMESTAMP, 67, 355);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (356, 366, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (356, 1, 2, 366, CURRENT_TIMESTAMP, 60, 356);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (357, 1840, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (357, 0, NULL, 1840, CURRENT_TIMESTAMP, 95, 357);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (358, 882, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (358, 1, 7, 882, CURRENT_TIMESTAMP, 65, 358);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (359, 1810, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (359, 0, NULL, 1810, CURRENT_TIMESTAMP, 78, 359);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (360, 676, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (360, 1, 4, 676, CURRENT_TIMESTAMP, 86, 360);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (361, 1730, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (361, 0, NULL, 1730, CURRENT_TIMESTAMP, 84, 361);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (362, 756, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (362, 1, 7, 756, CURRENT_TIMESTAMP, 85, 362);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (363, 1110, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (363, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 363);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (364, 1760, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (364, 0, NULL, 1760, CURRENT_TIMESTAMP, 73, 364);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (365, 1550, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (365, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 365);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (366, 1740, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (366, 0, NULL, 1740, CURRENT_TIMESTAMP, 58, 366);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (367, 1400, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (367, 0, NULL, 1400, CURRENT_TIMESTAMP, 91, 367);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (368, 1700, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (368, 0, NULL, 1700, CURRENT_TIMESTAMP, 88, 368);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (369, 1990, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (369, 0, NULL, 1990, CURRENT_TIMESTAMP, 63, 369);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (370, 164, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (370, 1, 1, 164, CURRENT_TIMESTAMP, 76, 370);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (371, 1056, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (371, 1, 8, 1056, CURRENT_TIMESTAMP, 64, 371);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (372, 735, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (372, 1, 5, 735, CURRENT_TIMESTAMP, 81, 372);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (373, 1550, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (373, 0, NULL, 1550, CURRENT_TIMESTAMP, 97, 373);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (374, 1110, CURRENT_TIMESTAMP, 6);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (374, 0, NULL, 1110, CURRENT_TIMESTAMP, 75, 374);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (375, 2140, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (375, 0, NULL, 2140, CURRENT_TIMESTAMP, 99, 375);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (376, 1320, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (376, 0, NULL, 1320, CURRENT_TIMESTAMP, 64, 376);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (377, 344, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (377, 1, 2, 344, CURRENT_TIMESTAMP, 92, 377);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (378, 796, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (378, 1, 4, 796, CURRENT_TIMESTAMP, 63, 378);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (379, 938, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (379, 1, 7, 938, CURRENT_TIMESTAMP, 82, 379);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (380, 1926, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (380, 1, 9, 1926, CURRENT_TIMESTAMP, 99, 380);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (381, 1430, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (381, 0, NULL, 1430, CURRENT_TIMESTAMP, 71, 381);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (382, 1470, CURRENT_TIMESTAMP, 2);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (382, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 382);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (383, 114, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (383, 1, 1, 114, CURRENT_TIMESTAMP, 61, 383);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (384, 1140, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (384, 0, NULL, 1140, CURRENT_TIMESTAMP, 61, 384);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (385, 654, CURRENT_TIMESTAMP, 10);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (385, 1, 6, 654, CURRENT_TIMESTAMP, 70, 385);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (386, 880, CURRENT_TIMESTAMP, 5);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (386, 1, 4, 880, CURRENT_TIMESTAMP, 83, 386);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (387, 973, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (387, 1, 7, 973, CURRENT_TIMESTAMP, 72, 387);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (388, 1830, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (388, 0, NULL, 1830, CURRENT_TIMESTAMP, 60, 388);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (389, 324, CURRENT_TIMESTAMP, 7);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (389, 1, 2, 324, CURRENT_TIMESTAMP, 74, 389);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (390, 1470, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (390, 0, NULL, 1470, CURRENT_TIMESTAMP, 81, 390);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (391, 790, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (391, 1, 5, 790, CURRENT_TIMESTAMP, 62, 391);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (392, 528, CURRENT_TIMESTAMP, 4);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (392, 1, 3, 528, CURRENT_TIMESTAMP, 73, 392);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (393, 184, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (393, 1, 1, 184, CURRENT_TIMESTAMP, 95, 393);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (394, 796, CURRENT_TIMESTAMP, 3);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (394, 1, 4, 796, CURRENT_TIMESTAMP, 63, 394);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (395, 399, CURRENT_TIMESTAMP, 9);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (395, 1, 3, 399, CURRENT_TIMESTAMP, 98, 395);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (396, 714, CURRENT_TIMESTAMP, 11);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (396, 1, 6, 714, CURRENT_TIMESTAMP, 90, 396);
INSERT INTO purchases (id, total_cost, date, customer_id) VALUES (397, 1640, CURRENT_TIMESTAMP, 8);
INSERT INTO purchased_items (id, is_borrowed, borrow_days, price, date, book_id, purchase_id) VALUES (397, 0, NULL, 1640, CURRENT_TIMESTAMP, 76, 397);

COMMIT;