spring:
  application:
    name: MioBook
  frontend:
    url: http://localhost:5173
    authCallbackPath: /auth/google/callback
  datasource:
    url: jdbc:mysql://localhost:3306/miobook?createDatabaseIfNotExist=true
    username: root
    password: NewPassword123!
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 604800 # 7d
  oauth:
    google:
      clientId: 312476898368-5t065nkj5j3miq5m8omg6osm7ldgcg24.apps.googleusercontent.com
      clientSecret: ${OAUTH_GOOGLE_CLIENT_SECRET}