spring:
  application:
    name: MioBook
  datasource:
    url: jdbc:mysql://localhost:3306/miobook?createDatabaseIfNotExist=true
    username: root
    password: NewPassword123!
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379